routes/web.php
<?php

use Illuminate\Support\Facades\Route;

Route::group(['as' => 'portal.',
		 'namespace' => 'Portal',
		 'middleware' => ['web']
		],function() {

    
	Route::get('generate/{code?}', [\App\Http\Controllers\Portal\MainController::class, 'generate'])->name('generate');
	Route::get('send-eor/{code?}', [\App\Http\Controllers\Portal\MainController::class, 'send_eor'])->name('send_eor');
	Route::get('/', [\App\Http\Controllers\Portal\MainController::class, 'index'])->name('index');
	
});

Route::group(['prefix' => 'digipep','as' => 'admin.digipep.', 'namespace' => 'System'],function(){
	Route::any('success/{code}', [\App\Http\Controllers\System\DigipepController::class, 'success'])->name('success');
	Route::any('cancel/{code}', [\App\Http\Controllers\System\DigipepController::class, 'cancel'])->name('cancel');
	Route::any('failed/{code}', [\App\Http\Controllers\System\DigipepController::class, 'failed'])->name('failed');
});

Route::group(['as' => 'admin.',
		 'namespace' => 'System',
		 'prefix' => 'admin',
		 'middleware' => ['web']
		],function() {

    
    Route::get('get-division', [\App\Http\Controllers\System\MerchantController::class, 'get_division'])->name('get_division');
    Route::get('get-office', [\App\Http\Controllers\System\OfficeController::class, 'get_office'])->name('get_office');

	Route::group(['middleware' => 'system.guest'], function(){

        Route::get('register', [\App\Http\Controllers\System\AuthController::class, 'register'])->name('register');
        Route::post('register', [\App\Http\Controllers\System\AuthController::class, 'store']);

        Route::get('login', [\App\Http\Controllers\System\AuthController::class, 'admin_login'])->name('login');
        Route::post('login', [\App\Http\Controllers\System\AuthController::class, 'authenticate']);

        Route::get('forgot-password', [\App\Http\Controllers\System\AuthController::class, 'forgot_password'])->name('forgot_password');
        Route::post('forgot-password', [\App\Http\Controllers\System\AuthController::class, 'forgot_pw']);

        Route::get('reset-password/{token?}', [\App\Http\Controllers\System\AuthController::class, 'reset_password'])->name('reset_password');
        Route::post('reset-password/{token?}', [\App\Http\Controllers\System\AuthController::class, 'update_password']);

        Route::get('submit-documents/{code}', [\App\Http\Controllers\System\AuthController::class, 'submit_documents'])->name('submit_documents');
        Route::post('submit-documents/{code}', [\App\Http\Controllers\System\AuthController::class, 'store_documents']);

	});

    Route::get('generate/{code?}', [\App\Http\Controllers\System\MainController::class, 'generate'])->name('generate');
    Route::get('vertical', [\App\Http\Controllers\System\MainController::class, 'vertical'])->name('vertical');
    Route::get('horizontal', [\App\Http\Controllers\System\MainController::class, 'horizontal'])->name('horizontal');

	Route::group(['middleware' => ['system.auth', 'system.prevent-back-history']],function(){
		
        Route::get('/', [\App\Http\Controllers\System\MainController::class, 'index'])->name('index');
        Route::get('/logout', [\App\Http\Controllers\System\AuthController::class, 'logout'])->name('logout');

		Route::group(['as' => 'profile.'],function(){
            Route::get('/edit-password', [\App\Http\Controllers\System\ProfileController::class, 'edit_password'])->name('edit_password');
            Route::post('/edit-password', [\App\Http\Controllers\System\ProfileController::class, 'update_password']);
		});

		Route::group(['prefix' => 'registrants','as' => 'registrant.'],function(){
            Route::get('/', [\App\Http\Controllers\System\RegistrantController::class, 'index'])->name('index');
            Route::get('show/{id?}', [\App\Http\Controllers\System\RegistrantController::class, 'show'])->name('show');
            Route::any('activate/{id?}', [\App\Http\Controllers\System\RegistrantController::class, 'activate'])->name('activate');
            Route::any('decline/{id?}', [\App\Http\Controllers\System\RegistrantController::class, 'decline'])->name('decline');
            Route::get('update-status', [\App\Http\Controllers\System\RegistrantController::class, 'updateStatus'])->name('update_status');
		});

		Route::group(['prefix' => 'accounts','as' => 'account.'],function(){
            Route::get('/', [\App\Http\Controllers\System\AccountController::class, 'index'])->name('index');
            Route::get('show/{id?}', [\App\Http\Controllers\System\AccountController::class, 'show'])->name('show');
            Route::get('change-status/{id?}', [\App\Http\Controllers\System\AccountController::class, 'update_status'])->name('update_status');
		});

		Route::group(['prefix' => 'transactions','as' => 'transaction.'],function(){
            Route::get('/', [\App\Http\Controllers\System\TransactionController::class, 'index'])->name('index');
			Route::get('show/{code?}', [\App\Http\Controllers\System\TransactionController::class, 'show'])->name('show');
			Route::get('download/{code?}', [\App\Http\Controllers\System\TransactionController::class, 'download'])->name('download');
			Route::get('create', [\App\Http\Controllers\System\TransactionController::class, 'create'])->name('create');
			Route::post('create', [\App\Http\Controllers\System\TransactionController::class, 'store']);
		});

		Route::group(['prefix' => 'business','as' => 'business.'],function(){
			Route::get('/', [\App\Http\Controllers\System\BusinessController::class, 'index'])->name('index');
			Route::get('show/{code?}', [\App\Http\Controllers\System\BusinessController::class, 'show'])->name('show');
			Route::get('create', [\App\Http\Controllers\System\BusinessController::class, 'create'])->name('create');
			Route::post('create', [\App\Http\Controllers\System\BusinessController::class, 'store'])->name('store');
			Route::get('change-status/{code?}', [\App\Http\Controllers\System\BusinessController::class, 'update_status'])->name('update_status');
		});

		Route::group(['prefix' => 'ledgers','as' => 'ledger.'],function(){
			Route::get('/', [\App\Http\Controllers\System\LedgerController::class, 'index'])->name('index');
			Route::get('show/{code?}', [\App\Http\Controllers\System\LedgerController::class, 'show'])->name('show');

			Route::get('print/{code?}', [\App\Http\Controllers\System\LedgerController::class, 'print'])->name('print');
			Route::get('create', [\App\Http\Controllers\System\LedgerController::class, 'create'])->name('create');
			Route::post('create', [\App\Http\Controllers\System\LedgerController::class, 'store']);

			Route::get('online/{code?}', [\App\Http\Controllers\System\LedgerController::class, 'online'])->name('online');
			Route::get('booklet/{code?}', [\App\Http\Controllers\System\LedgerController::class, 'booklet'])->name('booklet');

			Route::get('edit/{merchant_code}/{code?}', [\App\Http\Controllers\System\LedgerController::class, 'edit'])->name('edit');
			Route::post('edit/{merchant_code}/{code?}', [\App\Http\Controllers\System\LedgerController::class, 'update'])->name('update');

			Route::get('export', [\App\Http\Controllers\System\LedgerController::class, 'export'])->name('export');
		});

		Route::group(['prefix' => 'offices','as' => 'office.'],function(){
			Route::get('/', [\App\Http\Controllers\System\OfficeController::class, 'index'])->name('index');
			Route::get('create', [\App\Http\Controllers\System\OfficeController::class, 'create'])->name('create');
			Route::post('create', [\App\Http\Controllers\System\OfficeController::class, 'store']);
			Route::get('edit/{id?}', [\App\Http\Controllers\System\OfficeController::class, 'edit'])->name('edit');
			Route::post('edit/{id?}', [\App\Http\Controllers\System\OfficeController::class, 'update']);
			Route::any('delete/{id?}', [\App\Http\Controllers\System\OfficeController::class, 'delete'])->name('delete');
		});

		Route::group(['prefix' => 'tellers','as' => 'teller.'],function(){
			Route::get('/', [\App\Http\Controllers\System\TellerController::class, 'index'])->name('index');
			Route::get('create', [\App\Http\Controllers\System\TellerController::class, 'create'])->name('create');
			Route::post('create', [\App\Http\Controllers\System\TellerController::class, 'store']);
			Route::get('edit/{id?}', [\App\Http\Controllers\System\TellerController::class, 'edit'])->name('edit');
			Route::post('edit/{id?}', [\App\Http\Controllers\System\TellerController::class, 'update']);
			Route::any('delete/{id?}', [\App\Http\Controllers\System\TellerController::class, 'delete'])->name('delete');
		});

		Route::group(['prefix' => 'merchants','as' => 'merchant.'],function(){
			Route::get('/', [\App\Http\Controllers\System\MerchantController::class, 'index'])->name('index');
			Route::get('create', [\App\Http\Controllers\System\MerchantController::class, 'create'])->name('create');
			Route::post('create', [\App\Http\Controllers\System\MerchantController::class, 'store']);
			Route::get('edit/{id?}', [\App\Http\Controllers\System\MerchantController::class, 'edit'])->name('edit');
			Route::post('edit/{id?}', [\App\Http\Controllers\System\MerchantController::class, 'update'])->name('update');
			Route::any('delete/{id?}', [\App\Http\Controllers\System\MerchantController::class, 'delete'])->name('delete');

			Route::get('edit-details/{code?}', [\App\Http\Controllers\System\MerchantController::class, 'edit_details'])->name('edit_details');
			Route::post('edit-details/{code?}', [\App\Http\Controllers\System\MerchantController::class, 'update_details'])->name('update_details');
		});

		Route::group(['prefix' => 'terminals','as' => 'terminal.'],function(){
			Route::get('/', [\App\Http\Controllers\System\TerminalController::class, 'index'])->name('index');
			Route::get('create', [\App\Http\Controllers\System\TerminalController::class, 'create'])->name('create');
			Route::post('create', [\App\Http\Controllers\System\TerminalController::class, 'store'])->name('store');

app/Http/Controllers/System/AccountController.php
<?php 

namespace App\Http\Controllers\System;


use App\Http\Controllers\Controller;
/*
 * Models used in this Controller
 */
use App\Models\User;
use App\Models\UserDocument;
use App\Models\Merchant;

/*
 * Requests used in this Controller
 */
use App\Http\Requests\System\PageRequest;
/*
 * App Classes used in this Controller
 */

use Illuminate\Support\Str;
use Illuminate\Support\Carbon;
use Illuminate\Support\Facades\DB;

class AccountController extends Controller
{

    protected $data;
    protected $guard = 'admin';
    public function __construct()
    {
        
    }
    
    public function index(PageRequest $request)
    {
        $per_page = request('per_page', 10);
        $this->data['user'] = $request->user($this->guard);
        $this->data['keyword'] = Str::lower(request('keyword'));

        $first_record = User::orderBy('created_at', 'ASC')->first();
        $start_date = request('start_date', now()->startOfMonth());
        if($first_record) {
            $start_date = request('start_date', $first_record->created_at->format("Y-m-d"));
        }

        $this->data['start_date'] = Carbon::parse($start_date)->format("Y-m-d");
        $this->data['end_date'] = $this->data['end_date'] = Carbon::parse(request('end_date', now()))->format("Y-m-d");

        $this->data['accounts'] = User::keyword($this->data['keyword'])
            ->where('type', 'user')
            ->where(DB::raw("DATE(created_at)"), '>=', $this->data['start_date'])
            ->where(DB::raw("DATE(created_at)"), '<=', $this->data['end_date'])
            ->orderBy('created_at', "DESC")
            ->paginate($per_page);
                                        
        return view('system.account.index', $this->data);
    }

    public function show(PageRequest $request, $id = null)
    {
        $per_page = request('per_page', 10);
        $this->data['user'] = $request->user($this->guard);

        $this->data['account'] = User::find($id);
        $this->data['documents'] = UserDocument::where('user_id', $id)->get();
        $this->data['merchants'] = Merchant::where('owner_user_id', $this->data['account']->id)
            ->orderBy('created_at', "DESC")
            ->paginate($per_page);

        if(!$this->data['account']) {
            session()->flash('notification-status', "failed");
            session()->flash('notification-msg', "Registrant record not found.");
            return redirect()->route('admin.account.index');
        }
        return view('system.account.show', $this->data);
    }

    public function update_status(PageRequest $request, $id = null)
    {
        $user = User::find($id);

        if(!$user OR ($user AND $user->type == 'super_user')) {
            session()->flash('notification-status', "failed");
            session()->flash('notification-msg', "Record not found.");
            return redirect()->route('admin.account.index');
        }

        if($user->status == "inactive") {
            $user->status = "active";
            session()->flash('notification-msg', "Record was successfully activated.");
        } else {
            $user->status = "inactive";
            session()->flash('notification-msg', "Record was successfully deactivated.");
        }

        $user->save();

        session()->flash('notification-status', "success");
        return redirect()->route('admin.account.index');
    }
}

app/Http/Controllers/System/BusinessController.php
<?php 

namespace App\Http\Controllers\System;

use App\Http\Controllers\Controller;

/*
 * Models used in this Controller
 */
use App\Models\Merchant;
use App\Models\TransactionHeader;
use App\Models\BookletTransaction;
use App\Models\Section;
use App\Models\Division;

/*
 * Requests used in this Controller
 */
use App\Http\Requests\System\PageRequest;
use App\Http\Requests\System\BusinessRequest;

/*
 * App Classes used in this Controller
 */
use Illuminate\Support\Str;
use Illuminate\Support\Facades\DB;

class BusinessController extends Controller
{

    protected $data;
    protected $guard = 'admin';

    public function __construct()
    {
        $this->data['sections'] = ['' => "--Choose Section--"] + Section::pluck('name', 'code')->toArray();
        $this->data['divisions'] = ['' => "--Choose Division--"] + Division::pluck('name', 'code')->toArray();
    }
    
    public function index(PageRequest $request)
    {
        $per_page = request('per_page', 10);
        $this->data['user'] = $request->user($this->guard);

        $this->data['merchants'] = Merchant::where('owner_user_id', $this->data['user']->id)
            ->orderBy('created_at', "DESC")
            ->paginate($per_page);
        return view('system.business.index', $this->data);
    }

    public function show(PageRequest $request, $code = null)
    {
        $per_page = request('per_page', 10);
        $this->data['user'] = $request->user($this->guard);

        $this->data['merchant'] = Merchant::where('merchant_code', $code)->first();

        if(!$this->data['merchant']) {
            session()->flash('notification-status', "failed");
            session()->flash('notification-msg', "Business record not found.");
            return redirect()->route('admin.business.index');
        }

        $this->data['transactions'] = TransactionHeader::where('merchant_code', $code)->take(5)->get();
        $this->data['booklet_transaction'] = BookletTransaction::where('merchant_code', $code)->take(5)->get();

        return view('system.business.show', $this->data);
    }

    public function create(PageRequest $request)
    {
        $this->data['user'] = $request->user($this->guard);
        
        return view('system.business.create', $this->data);
    }

    public function store(BusinessRequest $request)
    {
        $user = $request->user($this->guard);
        try{
            DB::beginTransaction();
            $merchant = new Merchant;

            $merchant->section_code = request('section_code');
            $merchant->division_code = request('division_code');
            $merchant->owner_user_id = $user->id;
            $merchant->merchant_name = request('merchant_name');
            $merchant->merchant_code = Str::slug($merchant->merchant_name);
            $merchant->merchant_type = 'commercial';
            $merchant->address = request('address');
            $merchant->tin = request('tin');
            $merchant->tel_no = request('tel_no');
            $merchant->save();

            DB::commit();

            session()->flash('notification-status', "success");
            session()->flash('notification-msg', "New business has been created.");
            return redirect()->route('admin.business.index');

        }catch(\Exception $e){
            DB::rollBack();
            session()->flash('notification-status', "failed");
            session()->flash('notification-msg', "Server Error. Please try again.".$e->getMessage());
            return redirect()->back();
        }

    }

    public function update_status(PageRequest $request, $code = null)
    {
        $merchant = Merchant::where('merchant_code', $code)->first();

        if(!$merchant) {
            session()->flash('notification-status', "failed");
            session()->flash('notification-msg', "Business record not found.");
            return redirect()->route('admin.business.index');
        }

        if($merchant->status == 'active') {
            $merchant->status = 'inactive';
            goto callback;
        }

        $merchant->status = 'active';

        callback:
        $merchant->save();

        session()->flash('notification-status', "success");
        session()->flash('notification-msg', "Business was successfully" . ($merchant->status == "active" ? " activated." : " deactivated."));
        return redirect()->route('admin.business.index');
    }
}

resources/views/system/terminal/create.blade.php
@extends('system._layouts.main')

@section('breadcrumb')
<div class="breadcrumb">
  <h1>Terminal</h1>
  <ul>
      <li>Terminal</li>
  </ul>
</div>

<div class="separator-breadcrumb border-top"></div>
@stop

@section('content')
<div class="row">
  <div class="col-md-6">
    <div class="card o-hidden mb-4">
        <div class="card-header">
            <h3 class="w-50 float-left card-title m-0">Terminal Form</h3>
        </div>
        <div class="card-body">
          @include('system.components.notifications')
          <form action="" method="POST">
            {!!csrf_field()!!}
            <div class="form-group">
                <label for="input_terminal_number"><b>Terminal Number</b><code> [This is auto generated by the system]</code></label>
                <input type="text" class="form-control" id="input_terminal_number" placeholder="" value="{{old('terminal_number', $terminal_number)}}" name="terminal_number" readonly>
                @if($errors->first('terminal_number'))
                <p class="form-text text-danger">{{$errors->first('terminal_number')}}</p>
                @endif
            </div>

            <div class="form-group">
                <label for="input_merchant"><b>Merchant</b></label>
                {!!Form::select('merchant_id',$merchants,old('merchant_id'),['class' => "form-control",'id' => "input_merchant"])!!}
                @if($errors->first('merchant_id'))
                <p class="form-text text-danger">{{$errors->first('merchant_id')}}</p>
                @endif
            </div>

            <div class="form-group">
                <label for="input_office"><b>Office</b></label>
                {!!Form::select('office_code',$offices,old('office_code'),['class' => "form-control",'id' => "input_office"])!!}
                <input type="hidden" value="{{old('office_code')}}" id="input_office_code" />
                @if($errors->first('office_code'))
                <p class="form-text text-danger">{{$errors->first('office_code')}}</p>
                @endif
            </div>

            {{-- <div class="form-group">
                <label for="input_serial_code"><b>Serial Code</b></label>
                <input type="text" class="form-control" id="input_serial_code" placeholder="" value="{{old('serial_code')}}" name="serial_code" readonly>
                @if($errors->first('serial_code'))
                <p class="form-text text-danger">{{$errors->first('serial_code')}}</p>
                @endif
            </div> --}}

            <div class="form-group">
                <label for="input_device_name"><b>Device Name</b></label>
                <input type="text" class="form-control" id="input_device_name" placeholder="" value="{{old('device_name')}}" name="device_name">
                @if($errors->first('device_name'))
                <p class="form-text text-danger">{{$errors->first('device_name')}}</p>
                @endif
            </div>

            <div class="form-group">
                <label for="input_device_serial"><b>Device Serial</b></label>
                <input type="text" class="form-control" id="input_device_serial" placeholder="" value="{{old('device_serial')}}" name="device_serial">
                @if($errors->first('device_serial'))
                <p class="form-text text-danger">{{$errors->first('device_serial')}}</p>
                @endif
            </div>

            <div class="form-group">
              <a href="{{route('admin.terminal.index')}}" class="btn btn-secondary">Go back to Terminal List</a>
              <button type="submit" class="btn  btn-primary">Submit</button>
            </div>
          </form>
        </div>
    </div>
  </div>
</div>
@stop

@section('page-scripts')
<script type="text/javascript">
    $('#input_merchant').on('change', function(){
        $.ajax({
            url : "{{route('admin.get_office')}}",
            dataType : "json",
            data: {merchant_id : $(this).val()},
            type: "GET",
            success : function(data){
                if(data.offices){
                    $('#input_office').empty()
                    $('#input_office').append('<option value="">-- Choose Office --</option>');
                    $.each(data.offices,function(i, office){
                        if($('#input_office_code').val() == office.code)
                            $('#input_office').append('<option value="' + office.code +'" selected="selected">' + office.name +"</option>");
                        else
                            $('#input_office').append('<option value="' + office.code +'">' + office.name +"</option>");
                    });
                }else {

                }
            },  
            error : function(jqXHR,textStatus,thrownError){
            }
        });
    });

    @if(old('merchant_id'))
        $('#input_merchant').change();
    @endif
</script>
@endsection

resources/views/system/terminal/edit.blade.php
@extends('system._layouts.main')

@section('breadcrumb')
<div class="breadcrumb">
  <h1>Terminal</h1>
  <ul>
      <li>Update Terminal Details</li>
  </ul>
</div>

<div class="separator-breadcrumb border-top"></div>
@stop

@section('content')
<div class="row">
  <div class="col-md-6">
    <div class="card o-hidden mb-4">
        <div class="card-header">
            <h3 class="w-50 float-left card-title m-0">Update Terminal Form</h3>
        </div>
        <div class="card-body">
          @include('system.components.notifications')
          <form action="" method="POST">
            {!!csrf_field()!!}
            <div class="form-group">
                <label for="input_merchant"><b>Merchant</b></label>
                {!!Form::select('merchant_id',$merchants,old('merchant_id', $terminal->merchant_id),['class' => "form-control",'id' => "input_merchant"])!!}
                @if($errors->first('merchant_id'))
                <p class="form-text text-danger">{{$errors->first('merchant_id')}}</p>
                @endif
            </div>

            <div class="form-group">
                <label for="input_office"><b>Office</b></label>
                {!!Form::select('office_code',$offices,old('office_code', $terminal->office_code),['class' => "form-control",'id' => "input_office"])!!}
                <input type="hidden" value="{{old('office_code', $terminal->office_code)}}" id="input_office_code" />
                @if($errors->first('office_code'))
                <p class="form-text text-danger">{{$errors->first('office_code')}}</p>
                @endif
            </div>

            {{-- <div class="form-group">
                <label for="input_serial_code"><b>Serial Code</b></label>
                <input type="text" class="form-control" id="input_serial_code" placeholder="" value="{{old('serial_code', $terminal->serial_code)}}" name="serial_code">
                @if($errors->first('serial_code'))
                <p class="form-text text-danger">{{$errors->first('serial_code')}}</p>
                @endif
            </div> --}}

            <div class="form-group">
                <label for="input_device_name"><b>Device Name</b></label>
                <input type="text" class="form-control" id="input_device_name" placeholder="" value="{{old('device_name', $terminal->device_name)}}" name="device_name">
                @if($errors->first('device_name'))
                <p class="form-text text-danger">{{$errors->first('device_name')}}</p>
                @endif
            </div>

            <div class="form-group">
                <label for="input_device_serial"><b>Device Serial</b></label>
                <input type="text" class="form-control" id="input_device_serial" placeholder="" value="{{old('device_serial', $terminal->device_serial)}}" name="device_serial">
                @if($errors->first('device_serial'))
                <p class="form-text text-danger">{{$errors->first('device_serial')}}</p>
                @endif
            </div>

            <div class="form-group">
              <a href="{{route('admin.terminal.index')}}" class="btn btn-secondary">Go back to Terminal List</a>
              <button type="submit" class="btn  btn-primary">Submit</button>
            </div>
          </form>
        </div>
    </div>
  </div>
</div>
@stop

@section('page-scripts')
<script type="text/javascript">
    $('#input_merchant').on('change', function(){
        $.ajax({
            url : "{{route('admin.get_office')}}",
            dataType : "json",
            data: {merchant_id : $(this).val()},
            type: "GET",
            success : function(data){
                if(data.offices){
                    $('#input_office').empty()
                    $('#input_office').append('<option value="">-- Choose Office --</option>');
                    $.each(data.offices,function(i, office){
                        if($('#input_office_code').val() == office.code)
                            $('#input_office').append('<option value="' + office.code +'" selected="selected">' + office.name +"</option>");
                        else
                            $('#input_office').append('<option value="' + office.code +'">' + office.name +"</option>");
                    });
                }else {

                }
            },  
            error : function(jqXHR,textStatus,thrownError){
            }
        });
    }).change();
</script>
@endsection

resources/views/system/terminal/index.blade.php
@extends('system._layouts.main')

@section('breadcrumb')
<div class="breadcrumb">
  <h1>Terminal</h1>
  {{-- <ul>
      <li><a href="">Dashboard</a></li>
      <li>Version 1</li>
  </ul> --}}
</div>

<div class="separator-breadcrumb border-top"></div>
@stop

@section('content')
<div class="row">
  <div class="col-md-8">
    <div class="card o-hidden mb-4">
        <div class="card-header">
            <h3 class="w-50 float-left card-title m-0">Record Data </h3>
            <span class="float-right">
              <a href="{{route('admin.terminal.create')}}" class="btn btn-primary">Add Terminal</a>
            </span>
        </div>
        <div class="card-body">
            @include('system.components.notifications')
          
            <div class="table-responsive">
              <table class="table table-bordered text-center">
                <thead class="thead-dark">
                    <tr>
                        <th scope="col">Terminal Number</th>
                        <th scope="col">Serial Code</th>
                        <th scope="col">Device Name</th>
                        <th scope="col">Merchant</th>
                        <th scope="col">Office</th>
                        <th scope="col">Action</th>
                    </tr>
                </thead>
                <tbody>
                    @forelse($terminals as $index => $terminal)
                    <tr>
                        <td>{{$terminal->terminal_number}}</td>
                        <td>{{$terminal->serial_code}}</td>
                        <td>{{$terminal->device_name}}</td>
                        <td>{{$terminal->merchant ? $terminal->merchant->merchant_name : ''}}</td>
                        <td>{{$terminal->office ? $terminal->office->name : ''}}</td>
                        <td>
                            <div class="btn-group">
                              <button type="button" data-toggle="dropdown" class="btn btn-sm btn-secondary dropdown-toggle" aria-expanded="false">Actions <span class="icon-dropdown mdi mdi-chevron-down"></span></button>
                              <div class="dropdown-menu">
                                  <a class="dropdown-item" href="{{route('admin.terminal.edit',[$terminal->id])}}">Edit Details</a>
                              </div>
                            </div>
                        </td>
                    </tr>
                    @empty
                    <tr>
                      <td colspan="6"><div class="text-center"><i>No records found yet.</i></div></td>
                    </tr>
                    @endforelse
                </tbody>
            </table>
            </div>
        </div>
    </div>
  </div>
</div>
@stop