routes/web.php
<?php

use Illuminate\Support\Facades\Route;

Route::group(['as' => 'portal.',
		 'namespace' => 'Portal',
		 'middleware' => ['web']
		],function() {

    
	Route::get('generate/{code?}', [\App\Http\Controllers\Portal\MainController::class, 'generate'])->name('generate');
	Route::get('send-eor/{code?}', [\App\Http\Controllers\Portal\MainController::class, 'send_eor'])->name('send_eor');
	Route::get('/', [\App\Http\Controllers\Portal\MainController::class, 'index'])->name('index');
	
});

Route::group(['prefix' => 'digipep','as' => 'admin.digipep.', 'namespace' => 'System'],function(){
	Route::any('success/{code}', [\App\Http\Controllers\System\DigipepController::class, 'success'])->name('success');
	Route::any('cancel/{code}', [\App\Http\Controllers\System\DigipepController::class, 'cancel'])->name('cancel');
	Route::any('failed/{code}', [\App\Http\Controllers\System\DigipepController::class, 'failed'])->name('failed');
});

Route::group(['as' => 'admin.',
		 'namespace' => 'System',
		 'prefix' => 'admin',
		 'middleware' => ['web']
		],function() {

    
    Route::get('get-division', [\App\Http\Controllers\System\MerchantController::class, 'get_division'])->name('get_division');
    Route::get('get-office', [\App\Http\Controllers\System\OfficeController::class, 'get_office'])->name('get_office');

	Route::group(['middleware' => 'system.guest'], function(){

        Route::get('register', [\App\Http\Controllers\System\AuthController::class, 'register'])->name('register');
        Route::post('register', [\App\Http\Controllers\System\AuthController::class, 'store']);

        Route::get('login', [\App\Http\Controllers\System\AuthController::class, 'admin_login'])->name('login');
        Route::post('login', [\App\Http\Controllers\System\AuthController::class, 'authenticate']);

        Route::get('forgot-password', [\App\Http\Controllers\System\AuthController::class, 'forgot_password'])->name('forgot_password');
        Route::post('forgot-password', [\App\Http\Controllers\System\AuthController::class, 'forgot_pw']);

        Route::get('reset-password/{token?}', [\App\Http\Controllers\System\AuthController::class, 'reset_password'])->name('reset_password');
        Route::post('reset-password/{token?}', [\App\Http\Controllers\System\AuthController::class, 'update_password']);

        Route::get('submit-documents/{code}', [\App\Http\Controllers\System\AuthController::class, 'submit_documents'])->name('submit_documents');
        Route::post('submit-documents/{code}', [\App\Http\Controllers\System\AuthController::class, 'store_documents']);

	});

    Route::get('generate/{code?}', [\App\Http\Controllers\System\MainController::class, 'generate'])->name('generate');
    Route::get('vertical', [\App\Http\Controllers\System\MainController::class, 'vertical'])->name('vertical');
    Route::get('horizontal', [\App\Http\Controllers\System\MainController::class, 'horizontal'])->name('horizontal');

	Route::group(['middleware' => ['system.auth', 'system.prevent-back-history']],function(){
		
        Route::get('/', [\App\Http\Controllers\System\MainController::class, 'index'])->name('index');
        Route::get('/logout', [\App\Http\Controllers\System\AuthController::class, 'logout'])->name('logout');

		Route::group(['as' => 'profile.'],function(){
            Route::get('/edit-password', [\App\Http\Controllers\System\ProfileController::class, 'edit_password'])->name('edit_password');
            Route::post('/edit-password', [\App\Http\Controllers\System\ProfileController::class, 'update_password']);
		});

		Route::group(['prefix' => 'registrants','as' => 'registrant.'],function(){
            Route::get('/', [\App\Http\Controllers\System\RegistrantController::class, 'index'])->name('index');
            Route::get('show/{id?}', [\App\Http\Controllers\System\RegistrantController::class, 'show'])->name('show');
            Route::any('activate/{id?}', [\App\Http\Controllers\System\RegistrantController::class, 'activate'])->name('activate');
            Route::any('decline/{id?}', [\App\Http\Controllers\System\RegistrantController::class, 'decline'])->name('decline');
            Route::get('update-status', [\App\Http\Controllers\System\RegistrantController::class, 'updateStatus'])->name('update_status');
		});

		Route::group(['prefix' => 'accounts','as' => 'account.'],function(){
            Route::get('/', [\App\Http\Controllers\System\AccountController::class, 'index'])->name('index');
            Route::get('show/{id?}', [\App\Http\Controllers\System\AccountController::class, 'show'])->name('show');
            Route::get('change-status/{id?}', [\App\Http\Controllers\System\AccountController::class, 'update_status'])->name('update_status');
		});

		Route::group(['prefix' => 'transactions','as' => 'transaction.'],function(){
            Route::get('/', [\App\Http\Controllers\System\TransactionController::class, 'index'])->name('index');
			Route::get('show/{code?}', [\App\Http\Controllers\System\TransactionController::class, 'show'])->name('show');
			Route::get('download/{code?}', [\App\Http\Controllers\System\TransactionController::class, 'download'])->name('download');
			Route::get('create', [\App\Http\Controllers\System\TransactionController::class, 'create'])->name('create');
			Route::post('create', [\App\Http\Controllers\System\TransactionController::class, 'store']);
		});

		Route::group(['prefix' => 'business','as' => 'business.'],function(){
			Route::get('/', [\App\Http\Controllers\System\BusinessController::class, 'index'])->name('index');
			Route::get('show/{code?}', [\App\Http\Controllers\System\BusinessController::class, 'show'])->name('show');
			Route::get('create', [\App\Http\Controllers\System\BusinessController::class, 'create'])->name('create');
			Route::post('create', [\App\Http\Controllers\System\BusinessController::class, 'store'])->name('store');
			Route::get('change-status/{code?}', [\App\Http\Controllers\System\BusinessController::class, 'update_status'])->name('update_status');
		});

		Route::group(['prefix' => 'ledgers','as' => 'ledger.'],function(){
			Route::get('/', [\App\Http\Controllers\System\LedgerController::class, 'index'])->name('index');
			Route::get('show/{code?}', [\App\Http\Controllers\System\LedgerController::class, 'show'])->name('show');

			Route::get('print/{code?}', [\App\Http\Controllers\System\LedgerController::class, 'print'])->name('print');
			Route::get('create', [\App\Http\Controllers\System\LedgerController::class, 'create'])->name('create');
			Route::post('create', [\App\Http\Controllers\System\LedgerController::class, 'store']);

			Route::get('online/{code?}', [\App\Http\Controllers\System\LedgerController::class, 'online'])->name('online');
			Route::get('booklet/{code?}', [\App\Http\Controllers\System\LedgerController::class, 'booklet'])->name('booklet');

			Route::get('edit/{merchant_code}/{code?}', [\App\Http\Controllers\System\LedgerController::class, 'edit'])->name('edit');
			Route::post('edit/{merchant_code}/{code?}', [\App\Http\Controllers\System\LedgerController::class, 'update'])->name('update');

			Route::get('export', [\App\Http\Controllers\System\LedgerController::class, 'export'])->name('export');
		});

		Route::group(['prefix' => 'offices','as' => 'office.'],function(){
			Route::get('/', [\App\Http\Controllers\System\OfficeController::class, 'index'])->name('index');
			Route::get('create', [\App\Http\Controllers\System\OfficeController::class, 'create'])->name('create');
			Route::post('create', [\App\Http\Controllers\System\OfficeController::class, 'store']);
			Route::get('edit/{id?}', [\App\Http\Controllers\System\OfficeController::class, 'edit'])->name('edit');
			Route::post('edit/{id?}', [\App\Http\Controllers\System\OfficeController::class, 'update']);
			Route::any('delete/{id?}', [\App\Http\Controllers\System\OfficeController::class, 'delete'])->name('delete');
		});

		Route::group(['prefix' => 'tellers','as' => 'teller.'],function(){
			Route::get('/', [\App\Http\Controllers\System\TellerController::class, 'index'])->name('index');
			Route::get('create', [\App\Http\Controllers\System\TellerController::class, 'create'])->name('create');
			Route::post('create', [\App\Http\Controllers\System\TellerController::class, 'store']);
			Route::get('edit/{id?}', [\App\Http\Controllers\System\TellerController::class, 'edit'])->name('edit');
			Route::post('edit/{id?}', [\App\Http\Controllers\System\TellerController::class, 'update']);
			Route::any('delete/{id?}', [\App\Http\Controllers\System\TellerController::class, 'delete'])->name('delete');
		});

		Route::group(['prefix' => 'merchants','as' => 'merchant.'],function(){
			Route::get('/', [\App\Http\Controllers\System\MerchantController::class, 'index'])->name('index');
			Route::get('create', [\App\Http\Controllers\System\MerchantController::class, 'create'])->name('create');
			Route::post('create', [\App\Http\Controllers\System\MerchantController::class, 'store']);
			Route::get('edit/{id?}', [\App\Http\Controllers\System\MerchantController::class, 'edit'])->name('edit');
			Route::post('edit/{id?}', [\App\Http\Controllers\System\MerchantController::class, 'update'])->name('update');
			Route::any('delete/{id?}', [\App\Http\Controllers\System\MerchantController::class, 'delete'])->name('delete');

			Route::get('edit-details/{code?}', [\App\Http\Controllers\System\MerchantController::class, 'edit_details'])->name('edit_details');
			Route::post('edit-details/{code?}', [\App\Http\Controllers\System\MerchantController::class, 'update_details'])->name('update_details');
		});

		Route::group(['prefix' => 'terminals','as' => 'terminal.'],function(){
			Route::get('/', [\App\Http\Controllers\System\TerminalController::class, 'index'])->name('index');
			Route::get('create', [\App\Http\Controllers\System\TerminalController::class, 'create'])->name('create');
			Route::post('create', [\App\Http\Controllers\System\TerminalController::class, 'store'])->name('store');

app/Models/Merchant.php
<?php 

namespace App\Models;

use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\SoftDeletes;

class Merchant extends Model
{
    
    use SoftDeletes;
    
    /**
     * Enable soft delete in table
     *
     * @var boolean
     */
    protected $softDelete = true;
    
    /**
     * The database table used by the model.
     *
     * @var string
     */
    protected $table = 'merchants';

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [];


    /**
     * The attributes excluded from the model's JSON form.
     *
     * @var array
     */
    protected $hidden = [];

    /**
     * The attributes that created within the model.
     *
     * @var array
     */
    protected $appends = [];

    public function section()
    {
        return $this->belongsTo('App\Models\Section', 'section_code', 'code');
    }

    public function division()
    {
        return $this->belongsTo('App\Models\Division', 'division_code', 'code');
    }

    public function receipts()
    {
        return $this->hasMany(Receipt::class);
    }

    public function transactions()
    {
        return $this->hasMany('App\Models\TransactionHeader', 'merchant_code', 'merchant_code');
    }

    public function booklet_transactions()
    {
        return $this->hasMany('App\Models\BookletTransaction', 'merchant_code', 'merchant_code');
    }

    public function getAvailableOrAttribute()
    {
        $total_or_series = Order::where('merchant_code', $this->merchant_code)->where('status', 'COMPLETED')->sum('eor_online_qty');
        $total_used = TransactionHeader::where('merchant_code', $this->merchant_code)->count();

        return $total_or_series - $total_used;
    }

    public function getAvailableBookletAttribute()
    {
        $total_or_series = Order::where('merchant_code', $this->merchant_code)->where('status', 'COMPLETED')->sum('eor_booklet_qty');
        $total_used = BookletTransaction::where('merchant_code', $this->merchant_code)->where('status', 1)->count();
        
        return $total_or_series - $total_used;
    }

    public function scopeKeyword($query,$keyword = null)
    {
        if($keyword) {
            return $query->whereRaw("LOWER(merchant_name) LIKE '%{$keyword}%'")
                ->orWhereRaw("LOWER(merchant_code) LIKE '%{$keyword}%'");
        }
    }
}

app/Http/Controllers/Api/MerchantController.php
<?php

namespace App\Http\Controllers\Api;

use App\Http\Controllers\Controller;
use App\Http\Requests\Api\PageRequest;

use App\Models\Terminal;
use App\Models\Teller;
use App\Models\Merchant;
use App\Http\Resources\MerchantResource;

class MerchantController extends Controller
{
    protected $response = array();

    public function __construct()
    {

    }

    public function index(PageRequest $request)
    {
        return MerchantResource::collection(Merchant::all());
    }

    public function show(PageRequest $request, $id)
    {
        return new MerchantResource(Merchant::findOrFail($id));
    }
    
}

app/Http/Controllers/System/AccountController.php
<?php 

namespace App\Http\Controllers\System;


use App\Http\Controllers\Controller;
/*
 * Models used in this Controller
 */
use App\Models\User;
use App\Models\UserDocument;
use App\Models\Merchant;

/*
 * Requests used in this Controller
 */
use App\Http\Requests\System\PageRequest;
/*
 * App Classes used in this Controller
 */

use Illuminate\Support\Str;
use Illuminate\Support\Carbon;
use Illuminate\Support\Facades\DB;

class AccountController extends Controller
{

    protected $data;
    protected $guard = 'admin';
    public function __construct()
    {
        
    }
    
    public function index(PageRequest $request)
    {
        $per_page = request('per_page', 10);
        $this->data['user'] = $request->user($this->guard);
        $this->data['keyword'] = Str::lower(request('keyword'));

        $first_record = User::orderBy('created_at', 'ASC')->first();
        $start_date = request('start_date', now()->startOfMonth());
        if($first_record) {
            $start_date = request('start_date', $first_record->created_at->format("Y-m-d"));
        }

        $this->data['start_date'] = Carbon::parse($start_date)->format("Y-m-d");
        $this->data['end_date'] = $this->data['end_date'] = Carbon::parse(request('end_date', now()))->format("Y-m-d");

        $this->data['accounts'] = User::keyword($this->data['keyword'])
            ->where('type', 'user')
            ->where(DB::raw("DATE(created_at)"), '>=', $this->data['start_date'])
            ->where(DB::raw("DATE(created_at)"), '<=', $this->data['end_date'])
            ->orderBy('created_at', "DESC")
            ->paginate($per_page);
                                        
        return view('system.account.index', $this->data);
    }

    public function show(PageRequest $request, $id = null)
    {
        $per_page = request('per_page', 10);
        $this->data['user'] = $request->user($this->guard);

        $this->data['account'] = User::find($id);
        $this->data['documents'] = UserDocument::where('user_id', $id)->get();
        $this->data['merchants'] = Merchant::where('owner_user_id', $this->data['account']->id)
            ->orderBy('created_at', "DESC")
            ->paginate($per_page);

        if(!$this->data['account']) {
            session()->flash('notification-status', "failed");
            session()->flash('notification-msg', "Registrant record not found.");
            return redirect()->route('admin.account.index');
        }
        return view('system.account.show', $this->data);
    }

    public function update_status(PageRequest $request, $id = null)
    {
        $user = User::find($id);

        if(!$user OR ($user AND $user->type == 'super_user')) {
            session()->flash('notification-status', "failed");
            session()->flash('notification-msg', "Record not found.");
            return redirect()->route('admin.account.index');
        }

        if($user->status == "inactive") {
            $user->status = "active";
            session()->flash('notification-msg', "Record was successfully activated.");
        } else {
            $user->status = "inactive";
            session()->flash('notification-msg', "Record was successfully deactivated.");
        }

        $user->save();

        session()->flash('notification-status', "success");
        return redirect()->route('admin.account.index');
    }
}

app/Http/Controllers/System/Controller.php
<?php

namespace App\Http\Controllers\System;

use App\Http\Controllers\Controller as BaseController;

use Illuminate\Routing\Route;
use Illuminate\Support\Carbon;

use App\Services\Helper;

class Controller extends BaseController
{

    protected $data;

    public function __construct()
    {
        // self::set_system_routes();
        // self::set_user_info();
        // self::set_date_today();
        // self::set_current_route();
        // self::set_marital_status();
        // self::set_months();
        // self::set_years();
        // self::set_days();
    }

    public function get_data()
    {
        $this->data['page_title'] = "";
        return $this->data;
    }


    public function set_current_route()
    {
        $this->data['current_route'] = Route::currentRouteName();
    }

    public function set_date_today()
    {
        $this->data['date_today'] = Helper::date_db(now());
    }

    public function set_system_routes()
    {

    }
}

resources/views/system/merchant/create.blade.php
@extends('system._layouts.main')

@section('breadcrumb')
<div class="breadcrumb">
  <h1>Merchant</h1>
  <ul>
      <li>Merchant</li>
  </ul>
</div>

<div class="separator-breadcrumb border-top"></div>
@stop

@section('content')
<div class="row">
  <div class="col-md-6">
    <div class="card o-hidden mb-4">
        <div class="card-header">
            <h3 class="w-50 float-left card-title m-0">Merchant Form</h3>
        </div>
        <div class="card-body">
          @include('system.components.notifications')
          <form action="" method="POST">
            {!!csrf_field()!!}
            <div class="form-group">
                <label for="input_type"><b>Type</b></label>
                {!!Form::select('merchant_type',$types,old('merchant_type'),['class' => "form-control",'id' => "input_type"])!!}
                @if($errors->first('merchant_type'))
                <p class="form-text text-danger">{{$errors->first('merchant_type')}}</p>
                @endif
            </div>

            <div class="form-group">
                <label for="input_section_code"><b>Section</b></label>
                {!!Form::select('section_code',$sections,old('section_code'),['class' => "form-control",'id' => "input_section_code"])!!}
                @if($errors->first('section_code'))
                <p class="form-text text-danger">{{$errors->first('section_code')}}</p>
                @endif
            </div>

            <div class="form-group">
                <label for="input_division_code"><b>Division</b></label>
                {!!Form::select('division_code',$divisions,old('division_code'),['class' => "form-control",'id' => "input_division_code"])!!}
                <input type="hidden" value="{{old('division_code')}}" id="input_division" />
                @if($errors->first('division_code'))
                <p class="form-text text-danger">{{$errors->first('division_code')}}</p>
                @endif
            </div>

            <div class="form-group">
                <label for="input_owner_user_id"><b>Owner</b></label>
                {!!Form::select('owner_user_id',$owners,old('owner_user_id'),['class' => "form-control",'id' => "input_owner_user_id"])!!}
                @if($errors->first('owner_user_id'))
                <p class="form-text text-danger">{{$errors->first('owner_user_id')}}</p>
                @endif
            </div>

            <div class="form-group">
                <label for="input_merchant_code"><b>Merchant Code</b></label>
                <input type="text" class="form-control" id="input_merchant_code" placeholder="" value="{{old('merchant_code')}}" name="merchant_code">
                @if($errors->first('merchant_code'))
                <p class="form-text text-danger">{{$errors->first('merchant_code')}}</p>
                @endif
            </div>

            <div class="form-group">
                <label for="input_merchant_name"><b>Merchant Name</b></label>
                <input type="text" class="form-control" id="input_merchant_name" placeholder="" value="{{old('merchant_name')}}" name="merchant_name">
                @if($errors->first('merchant_name'))
                <p class="form-text text-danger">{{$errors->first('merchant_name')}}</p>
                @endif
            </div>

            <div class="form-group">
                <label for="input_sub_merchant_code"><b>Submerchant Code</b></label>
                <input type="text" class="form-control" id="input_sub_merchant_code" placeholder="" value="{{old('submerchant_code')}}" name="submerchant_code">
                @if($errors->first('submerchant_code'))
                <p class="form-text text-danger">{{$errors->first('submerchant_code')}}</p>
                @endif
            </div>

            <div class="form-group">
                <label for="input_sub_merchant_name"><b>Submerchant Name</b></label>
                <input type="text" class="form-control" id="input_sub_merchant_name" placeholder="" value="{{old('submerchant_name')}}" name="submerchant_name">
                @if($errors->first('submerchant_name'))
                <p class="form-text text-danger">{{$errors->first('submerchant_name')}}</p>
                @endif
            </div>

            <div class="form-group">
                <label for="input_address"><b>Address</b></label>
                <input type="text" class="form-control" id="input_address" placeholder="" value="{{old('address')}}" name="address">
                @if($errors->first('address'))
                <p class="form-text text-danger">{{$errors->first('address')}}</p>
                @endif
            </div>

            <div class="form-group">
                <label for="input_tin"><b>Tin</b></label>
                <input type="text" class="form-control" id="input_tin" placeholder="000-000-000-000" value="{{old('tin')}}" name="tin">
                @if($errors->first('tin'))
                <p class="form-text text-danger">{{$errors->first('tin')}}</p>
                @endif
            </div>

            <div class="form-group">
                <label for="input_tel_no"><b>Telephone No.</b></label>
                <input type="text" class="form-control" id="input_tel_no" placeholder="(XX) XXXX-XXXX / +63 9XX-XXX-XXX" value="{{old('tel_no')}}" name="tel_no">
                @if($errors->first('tel_no'))
                <p class="form-text text-danger">{{$errors->first('tel_no')}}</p>
                @endif
            </div>

            <div class="form-group">
                <label for="input_max_online"><b>Max. Online Series</b></label>
                <input type="number" class="form-control" id="input_max_online" placeholder="" value="{{old('max_online')}}" name="max_online">
                @if($errors->first('max_online'))
                <p class="form-text text-danger">{{$errors->first('max_online')}}</p>
                @endif
            </div>

            <div class="form-group">
                <label for="input_max_booklet"><b>Max. Booklet Series (x50)</b></label>
                <input type="number" class="form-control" id="input_max_booklet" placeholder="" value="{{old('max_booklet')}}" name="max_booklet">
                @if($errors->first('max_booklet'))
                <p class="form-text text-danger">{{$errors->first('max_booklet')}}</p>
                @endif
            </div>

            <div class="form-group">
              <a href="{{route('admin.merchant.index')}}" class="btn btn-secondary">Go back to Merchant List</a>
              <button type="submit" class="btn  btn-primary">Submit</button>
            </div>
          </form>
        </div>
    </div>
  </div>
</div>
@stop

@section('page-scripts')
<script type="text/javascript">
    $('#input_section_code').on('change', function(){
        $.ajax({
            url : "{{route('admin.get_division')}}",
            dataType : "json",
            data: {code : $(this).val()},
            type: "GET",
            success : function(data){
                if(data.divisions){
                    $('#input_division_code').empty()
                    $('#input_division_code').append('<option value="">-- Choose Division --</option>');
                    $.each(data.divisions,function(i, division){
                        if($('#input_division').val() == division.code)
                            $('#input_division_code').append('<option value="' + division.code +'" selected="selected">' + division.name +"</option>");
                        else
                            $('#input_division_code').append('<option value="' + division.code +'">' + division.name +"</option>");
                    });
                }else {

                }
            },  
            error : function(jqXHR,textStatus,thrownError){
            }
        });
    });

    @if(old('section_code'))
        $('#input_section_code').change();
    @endif
</script>
@endsection

resources/views/system/merchant/index.blade.php
@extends('system._layouts.main')

@section('breadcrumb')
<div class="breadcrumb">
  <h1>Merchant</h1>
  {{-- <ul>
      <li><a href="">Dashboard</a></li>
      <li>Version 1</li>
  </ul> --}}
</div>

<div class="separator-breadcrumb border-top"></div>
@stop

@section('content')
<div class="row">
  <div class="col-md-12">
    <div class="card mb-5">
        <div class="card-header">
            <h3 class="w-50 float-left card-title m-0">Advance Filters </h3>
            <span class="float-right">
              <a href="{{route('admin.merchant.index')}}" class="btn btn-default btn-sm">[Reset Filter]</a>

            </span>
        </div>
        <form action="" method="GET">
        <div class="card-body">
            <div class="row row-xs mb-4">
              <div class="col-md-3">
                <label for="">Keyword <small>(Name, Code)</small></label>
                <input type="text" class="form-control" placeholder="Keyword" name="keyword" value="{{$keyword}}">
              </div>
              <div class="col-md-3">
                  <label for="">Transaction Date Range</label>
                  <input type="text" class="form-control datepicker" placeholder="Start Date" name="start_date" value="{{$start_date}}">
              </div>
              <div class="col-md-3 mt-3 mt-md-0">
                  <label for="">&nbsp;</label>
                  <input type="text" class="form-control datepicker" placeholder="End Date" name="end_date" value="{{$end_date}}">
              </div>
              <div class="col-md-3 mt-3 mt-md-0">
                  <label for="">&nbsp;</label>
                  <button type="submit" class="btn btn-primary btn-block">Apply Filters</button>
              </div>
            </div>
        </div>
        </form>
    </div>
    <div class="card o-hidden mb-4">
        <div class="card-header">
            <h3 class="w-50 float-left card-title m-0">Record Data </h3>
            @if(in_array($user->type, ['super_user', 'admin']))
            <span class="float-right">
              <a href="{{route('admin.merchant.create')}}" class="btn btn-primary">Add Merchant</a>
            </span>
            @endif
        </div>
        <div class="card-body">
            @include('system.components.notifications')
          
            <div class="table-responsive">
              <table class="table table-bordered text-center">
                <thead class="thead-dark">
                    <tr>
                        <th scope="col">Merchant Name</th>
                        <th scope="col">Merchant Code</th>
                        <th scope="col">Section</th>
                        <th scope="col">Division</th>
                        <th scope="col">Type</th>
                        <th scope="col">Available eOR Series</th>
                        <th scope="col">Available Booklet Series</th>
                        <th scope="col">Action</th>
                    </tr>
                </thead>
                <tbody>
                    @forelse($merchants as $index => $merchant)
                    <tr>
                        <td>{{$merchant->merchant_name}}</td>
                        <td>{{$merchant->merchant_code}}</td>
                        <td>{{$merchant->section ? $merchant->section->name : '-'}}</td>
                        <td>{{$merchant->division ? $merchant->division->name : '-'}}</td>
                        <td>{{ $merchant->merchant_type == 'govt' ? 'Government' : 'Commercial' }}</td>
                        <td>{{ $merchant->merchant_type == 'govt' ? '---' : $merchant->available_or }}</td>
                        <td>{{ $merchant->merchant_type == 'govt' ? '---' : $merchant->available_booklet }}</td>
                        <td>
                            <div class="btn-group">
                              <button type="button" data-toggle="dropdown" class="btn btn-sm btn-secondary dropdown-toggle" aria-expanded="false">Actions <span class="icon-dropdown mdi mdi-chevron-down"></span></button>
                              @if(in_array($user->type, ['super_user', 'admin']))
                              <div class="dropdown-menu">
                                  <a class="dropdown-item" href="{{route('admin.merchant.edit',[$merchant->id])}}">Edit Details</a>
                              </div>
                              @endif
                              @if(in_array($user->type, ['staff']))
                              <div class="dropdown-menu">
                                  <a class="dropdown-item" href="{{route('admin.merchant.edit_details',[$merchant->merchant_code])}}">Edit Details</a>
                              </div>
                              @endif
                            </div>
                        </td>
                    </tr>
                    @empty
                    <tr>
                      <td colspan="8"><div class="text-center"><i>No records found yet.</i></div></td>
                    </tr>
                    @endforelse
                </tbody>
            </table>
            {!! $merchants->appends(request()->query())->render() !!}
            </div>
        </div>
    </div>
  </div>
</div>
@stop

@section('page-styles')
<link rel="stylesheet" href="{{asset('assets/css/pickadate/classic.css',env('SECURE_ASSET',FALSE))}}">
<link rel="stylesheet" href="{{asset('assets/css/pickadate/classic.date.css',env('SECURE_ASSET',FALSE))}}">
<style type="text/css" media="screen">
  .table-responsive div a:hover{ text-decoration: underline; font-size: 600; }  
</style>
@stop

@section('page-scripts')
<script src="{{asset('assets/js/vendor/pickadate/picker.js',env('SECURE_ASSET',FALSE))}}"></script>
<script src="{{asset('assets/js/vendor/pickadate/picker.date.js',env('SECURE_ASSET',FALSE))}}"></script>
<script type="text/javascript">
  $(function(){

    $(".datepicker").pickadate({
      format: 'yyyy-mm-dd',
    });
  })
</script>
@stop