routes/web.php
<?php

use Illuminate\Support\Facades\Route;

Route::group(['as' => 'portal.',
		 'namespace' => 'Portal',
		 'middleware' => ['web']
		],function() {

    
	Route::get('generate/{code?}', [\App\Http\Controllers\Portal\MainController::class, 'generate'])->name('generate');
	Route::get('send-eor/{code?}', [\App\Http\Controllers\Portal\MainController::class, 'send_eor'])->name('send_eor');
	Route::get('/', [\App\Http\Controllers\Portal\MainController::class, 'index'])->name('index');
	
});

Route::group(['prefix' => 'digipep','as' => 'admin.digipep.', 'namespace' => 'System'],function(){
	Route::any('success/{code}', [\App\Http\Controllers\System\DigipepController::class, 'success'])->name('success');
	Route::any('cancel/{code}', [\App\Http\Controllers\System\DigipepController::class, 'cancel'])->name('cancel');
	Route::any('failed/{code}', [\App\Http\Controllers\System\DigipepController::class, 'failed'])->name('failed');
});

Route::group(['as' => 'admin.',
		 'namespace' => 'System',
		 'prefix' => 'admin',
		 'middleware' => ['web']
		],function() {

    
    Route::get('get-division', [\App\Http\Controllers\System\MerchantController::class, 'get_division'])->name('get_division');
    Route::get('get-office', [\App\Http\Controllers\System\OfficeController::class, 'get_office'])->name('get_office');

	Route::group(['middleware' => 'system.guest'], function(){

        Route::get('register', [\App\Http\Controllers\System\AuthController::class, 'register'])->name('register');
        Route::post('register', [\App\Http\Controllers\System\AuthController::class, 'store']);

        Route::get('login', [\App\Http\Controllers\System\AuthController::class, 'admin_login'])->name('login');
        Route::post('login', [\App\Http\Controllers\System\AuthController::class, 'authenticate']);

        Route::get('forgot-password', [\App\Http\Controllers\System\AuthController::class, 'forgot_password'])->name('forgot_password');
        Route::post('forgot-password', [\App\Http\Controllers\System\AuthController::class, 'forgot_pw']);

        Route::get('reset-password/{token?}', [\App\Http\Controllers\System\AuthController::class, 'reset_password'])->name('reset_password');
        Route::post('reset-password/{token?}', [\App\Http\Controllers\System\AuthController::class, 'update_password']);

        Route::get('submit-documents/{code}', [\App\Http\Controllers\System\AuthController::class, 'submit_documents'])->name('submit_documents');
        Route::post('submit-documents/{code}', [\App\Http\Controllers\System\AuthController::class, 'store_documents']);

	});

    Route::get('generate/{code?}', [\App\Http\Controllers\System\MainController::class, 'generate'])->name('generate');
    Route::get('vertical', [\App\Http\Controllers\System\MainController::class, 'vertical'])->name('vertical');
    Route::get('horizontal', [\App\Http\Controllers\System\MainController::class, 'horizontal'])->name('horizontal');

	Route::group(['middleware' => ['system.auth', 'system.prevent-back-history']],function(){
		
        Route::get('/', [\App\Http\Controllers\System\MainController::class, 'index'])->name('index');
        Route::get('/logout', [\App\Http\Controllers\System\AuthController::class, 'logout'])->name('logout');

		Route::group(['as' => 'profile.'],function(){
            Route::get('/edit-password', [\App\Http\Controllers\System\ProfileController::class, 'edit_password'])->name('edit_password');
            Route::post('/edit-password', [\App\Http\Controllers\System\ProfileController::class, 'update_password']);
		});

		Route::group(['prefix' => 'registrants','as' => 'registrant.'],function(){
            Route::get('/', [\App\Http\Controllers\System\RegistrantController::class, 'index'])->name('index');
            Route::get('show/{id?}', [\App\Http\Controllers\System\RegistrantController::class, 'show'])->name('show');
            Route::any('activate/{id?}', [\App\Http\Controllers\System\RegistrantController::class, 'activate'])->name('activate');
            Route::any('decline/{id?}', [\App\Http\Controllers\System\RegistrantController::class, 'decline'])->name('decline');
            Route::get('update-status', [\App\Http\Controllers\System\RegistrantController::class, 'updateStatus'])->name('update_status');
		});

		Route::group(['prefix' => 'accounts','as' => 'account.'],function(){
            Route::get('/', [\App\Http\Controllers\System\AccountController::class, 'index'])->name('index');
            Route::get('show/{id?}', [\App\Http\Controllers\System\AccountController::class, 'show'])->name('show');
            Route::get('change-status/{id?}', [\App\Http\Controllers\System\AccountController::class, 'update_status'])->name('update_status');
		});

		Route::group(['prefix' => 'transactions','as' => 'transaction.'],function(){
            Route::get('/', [\App\Http\Controllers\System\TransactionController::class, 'index'])->name('index');
			Route::get('show/{code?}', [\App\Http\Controllers\System\TransactionController::class, 'show'])->name('show');
			Route::get('download/{code?}', [\App\Http\Controllers\System\TransactionController::class, 'download'])->name('download');
			Route::get('create', [\App\Http\Controllers\System\TransactionController::class, 'create'])->name('create');
			Route::post('create', [\App\Http\Controllers\System\TransactionController::class, 'store']);
		});

		Route::group(['prefix' => 'business','as' => 'business.'],function(){
			Route::get('/', [\App\Http\Controllers\System\BusinessController::class, 'index'])->name('index');
			Route::get('show/{code?}', [\App\Http\Controllers\System\BusinessController::class, 'show'])->name('show');
			Route::get('create', [\App\Http\Controllers\System\BusinessController::class, 'create'])->name('create');
			Route::post('create', [\App\Http\Controllers\System\BusinessController::class, 'store'])->name('store');
			Route::get('change-status/{code?}', [\App\Http\Controllers\System\BusinessController::class, 'update_status'])->name('update_status');
		});

		Route::group(['prefix' => 'ledgers','as' => 'ledger.'],function(){
			Route::get('/', [\App\Http\Controllers\System\LedgerController::class, 'index'])->name('index');
			Route::get('show/{code?}', [\App\Http\Controllers\System\LedgerController::class, 'show'])->name('show');

			Route::get('print/{code?}', [\App\Http\Controllers\System\LedgerController::class, 'print'])->name('print');
			Route::get('create', [\App\Http\Controllers\System\LedgerController::class, 'create'])->name('create');
			Route::post('create', [\App\Http\Controllers\System\LedgerController::class, 'store']);

			Route::get('online/{code?}', [\App\Http\Controllers\System\LedgerController::class, 'online'])->name('online');
			Route::get('booklet/{code?}', [\App\Http\Controllers\System\LedgerController::class, 'booklet'])->name('booklet');

			Route::get('edit/{merchant_code}/{code?}', [\App\Http\Controllers\System\LedgerController::class, 'edit'])->name('edit');
			Route::post('edit/{merchant_code}/{code?}', [\App\Http\Controllers\System\LedgerController::class, 'update'])->name('update');

			Route::get('export', [\App\Http\Controllers\System\LedgerController::class, 'export'])->name('export');
		});

		Route::group(['prefix' => 'offices','as' => 'office.'],function(){
			Route::get('/', [\App\Http\Controllers\System\OfficeController::class, 'index'])->name('index');
			Route::get('create', [\App\Http\Controllers\System\OfficeController::class, 'create'])->name('create');
			Route::post('create', [\App\Http\Controllers\System\OfficeController::class, 'store']);
			Route::get('edit/{id?}', [\App\Http\Controllers\System\OfficeController::class, 'edit'])->name('edit');
			Route::post('edit/{id?}', [\App\Http\Controllers\System\OfficeController::class, 'update']);
			Route::any('delete/{id?}', [\App\Http\Controllers\System\OfficeController::class, 'delete'])->name('delete');
		});

		Route::group(['prefix' => 'tellers','as' => 'teller.'],function(){
			Route::get('/', [\App\Http\Controllers\System\TellerController::class, 'index'])->name('index');
			Route::get('create', [\App\Http\Controllers\System\TellerController::class, 'create'])->name('create');
			Route::post('create', [\App\Http\Controllers\System\TellerController::class, 'store']);
			Route::get('edit/{id?}', [\App\Http\Controllers\System\TellerController::class, 'edit'])->name('edit');
			Route::post('edit/{id?}', [\App\Http\Controllers\System\TellerController::class, 'update']);
			Route::any('delete/{id?}', [\App\Http\Controllers\System\TellerController::class, 'delete'])->name('delete');
		});

		Route::group(['prefix' => 'merchants','as' => 'merchant.'],function(){
			Route::get('/', [\App\Http\Controllers\System\MerchantController::class, 'index'])->name('index');
			Route::get('create', [\App\Http\Controllers\System\MerchantController::class, 'create'])->name('create');
			Route::post('create', [\App\Http\Controllers\System\MerchantController::class, 'store']);
			Route::get('edit/{id?}', [\App\Http\Controllers\System\MerchantController::class, 'edit'])->name('edit');
			Route::post('edit/{id?}', [\App\Http\Controllers\System\MerchantController::class, 'update'])->name('update');
			Route::any('delete/{id?}', [\App\Http\Controllers\System\MerchantController::class, 'delete'])->name('delete');

			Route::get('edit-details/{code?}', [\App\Http\Controllers\System\MerchantController::class, 'edit_details'])->name('edit_details');
			Route::post('edit-details/{code?}', [\App\Http\Controllers\System\MerchantController::class, 'update_details'])->name('update_details');
		});

		Route::group(['prefix' => 'terminals','as' => 'terminal.'],function(){
			Route::get('/', [\App\Http\Controllers\System\TerminalController::class, 'index'])->name('index');
			Route::get('create', [\App\Http\Controllers\System\TerminalController::class, 'create'])->name('create');
			Route::post('create', [\App\Http\Controllers\System\TerminalController::class, 'store'])->name('store');

app/Http/Controllers/Portal/AdministratorController.php
<?php 

namespace App\Http\Controllers\Portal;

/*
 * Models used in this Controller
 */
use App\Models\User as Account;

/*
 * Requests used in this Controller
 */
use App\Http\Requests\Portal\AdministratorRequest;
use App\Http\Requests\Portal\AdministratorPasswordRequest;
use App\Http\Requests\Portal\PageRequest;

/*
 * App Classes used in this Controller
 */
use Illuminate\Support\Str;
use Illuminate\Support\Facades\DB;

class AdministratorController extends Controller
{

    protected $data;
    public function __construct()
    {
        parent::__construct();
        array_merge($this->data, parent::get_data());
        $this->data['statuses'] = ['' => "--Choose Status--",'active' => "Active",'inactive' => "Inactive"];
    }
    
    public function index(PageRequest $request)
    {
        $per_page = request('per_page', 10);
        $this->data['accounts'] = Account::where('id', '<>', 1)->orderBy('created_at', "DESC")->paginate($per_page);
        return view('portal.administrator.index', $this->data);
    }

    public function create()
    {
        return view('portal.administrator.create', $this->data);
    }

    public function store(AdministratorRequest $request)
    {
        try{
            DB::beginTransaction();
            $account = new Account;
            $account->name = request('name');
            $account->username = Str::lower(request('username'));
            $account->email = Str::lower(request('email'));
            $account->password = bcrypt(request('password'));
            $account->status = request('status');
            $account->save();

            DB::commit();

            session()->flash('notification-status', "success");
            session()->flash('notification-msg', "New account has been created.");
            return redirect()->route('portal.administrator.index');

        }catch(\Exception $e){
            DB::rollBack();
            session()->flash('notification-status', "failed");
            session()->flash('notification-msg', "Server Error. Please try again.".$e->getMessage());
            return redirect()->back();
        }

    }

    public function edit($administrator_id = null)
    {
        $this->data['account'] = Account::find($administrator_id);

        if(!$this->data['account']) {
            session()->flash('notification-status', "failed");
            session()->flash('notification-msg', "Account not found.");
            return redirect()->route('portal.administrator.index');
        }
        return view('portal.administrator.edit', $this->data);
    }

    public function update(AdministratorRequest $request, $administrator_id = null)
    {
        $account = Account::find($administrator_id);

        if(!$account) {
            session()->flash('notification-status', "failed");
            session()->flash('notification-msg', "Account not found.");
            return redirect()->route('portal.administrator.index');
        }
        try{
            DB::beginTransaction();
            $account->name = request('name');
            $account->username = Str::lower(request('username'));
            $account->email = Str::lower(request('email'));
            $account->status = request('status');
            $account->save();

            DB::commit();

            session()->flash('notification-status', "success");
            session()->flash('notification-msg', "Account has been modified.");
            return redirect()->route('portal.administrator.index');

        }catch(\Exception $e){
            DB::rollBack();
            session()->flash('notification-status', "failed");
            session()->flash('notification-msg', "Server Error. Please try again.".$e->getMessage());
            return redirect()->back();
        }

    }

    public function reset_password($administrator_id = null)
    {
        $this->data['account'] = Account::find($administrator_id);

        if(!$this->data['account']) {
            session()->flash('notification-status', "failed");
            session()->flash('notification-msg', "Account not found.");
            return redirect()->route('portal.administrator.index');
        }
        return view('portal.administrator.reset-password', $this->data);
    }

    public function update_reset_password(AdministratorPasswordRequest $request,$administrator_id)
    {

        $account = Account::find($administrator_id);

        if(!$account) {
            session()->flash('notification-status', "failed");
            session()->flash('notification-msg', "Account not found.");
            return redirect()->route('portal.administrator.index');
        }

        try{
            DB::beginTransaction();
            $account->password = bcrypt(request('password'));
            $account->save();

            DB::commit();

            session()->flash('notification-status', "success");
            session()->flash('notification-msg', "New password has been configured.");
            return redirect()->route('portal.administrator.index');

        }catch(\Exception $e){
            DB::rollBack();
            session()->flash('notification-status', "failed");
            session()->flash('notification-msg', "Server Error. Please try again.".$e->getMessage());
            return redirect()->back();
        }

    }
}

app/Http/Controllers/Portal/AuthController.php
<?php 

namespace App\Http\Controllers\Portal;


/*
 * Requests used in this Controller
 */
use App\Http\Requests\Portal\PageRequest;

/*
 * App Classes used in this Controller
 */
use Illuminate\Support\Facades\Auth;


class AuthController extends Controller
{

    protected $data;
    
    public function login(PageRequest $request)
    {
        session()->put('admin_login', "no");
        return view('portal.auth.login');
    }

    public function admin_login(PageRequest $request)
    {
        session()->put('admin_login', "yes");
        return view('portal.auth.login');
    }

    public function authenticate(PageRequest $request)
    {
        $username = request('username');
        $password = request('password');
        $remember = request('remember_me', 1);

        $field = filter_var($username, FILTER_VALIDATE_EMAIL) ? 'email' : 'username';

        $guard = "partner";
        if(session()->get('admin_login', 'no') == "yes") {
            $guard = "admin";
        }

        $attempt = Auth::guard($guard)->attempt(['username' => $username, 'password' => $password], $remember);

        if($attempt) {
            session()->put('is_admin', 'no');

            if(session()->get('admin_login', 'no') == "yes") {
                session()->put('is_admin', 'yes');
            }

            $user = Auth::guard($guard)->user();
            if($user->status != "active") {
                Auth::guard($guard)->logout();
                session()->flash('notification-status', 'warning');
                session()->flash('notification-msg', 'Account is not yet active.');
                goto callback;
            }

            session()->forget('admin_login');

            session()->flash('notification-status', 'success');
            session()->flash('notification-msg', 'Login successfully.');

            return redirect()->route('portal.index');
        }

        session()->flash('notification-status', "failed");
        session()->flash('notification-msg', "Invalid account credentials.");

        callback:
        return redirect()->back();

    }

    public function logout()
    {
        $guard = "partner";
        $route = "portal.login";

        if(session()->get('is_admin', 'no') == "yes") {
            $guard = "admin";
            $route = "portal.admin_login";

        }

        Auth::guard($guard)->logout();

        session()->flash('notification-status', 'success');
        session()->flash('notification-msg', 'You are now signed off.');
        return redirect()->route($route);
    }
}

resources/views/portal/components/header.blade.php
<div class="main-header">
    <div class="logo">
        <img src="{{asset('assets/images/logo.png?v=1.1')}}" alt="">
    </div>

    <div class="menu-toggle">
        <div></div>
                <div></div>
        <div></div>
    </div>

    <div style="margin: auto"></div>

    <div class="header-part-right">
        {{-- <i class="i-Full-Screen header-icon d-none d-sm-inline-block" data-fullscreen></i>
        <div class="dropdown widget_dropdown">
            <i class="i-Safe-Box text-muted header-icon" role="button" id="dropdownMenuButton" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false"></i>
            <div class="dropdown-menu" aria-labelledby="dropdownMenuButton">
                <div class="menu-icon-grid">
                    <a href="index.html#"><i class="i-Shop-4"></i> Home</a>
                    <a href="index.html#"><i class="i-Library"></i> UI Kits</a>
                    <a href="index.html#"><i class="i-Drop"></i> Apps</a>
                    <a href="index.html#"><i class="i-File-Clipboard-File--Text"></i> Forms</a>
                    <a href="index.html#"><i class="i-Checked-User"></i> Sessions</a>
                    <a href="index.html#"><i class="i-Ambulance"></i> Support</a>
                </div>
            </div>
        </div> --}}
        <div>Hi <span class="text-primary">{{Auth::guard((session()->get('is_admin','no') == "yes" ?'admin' : 'partner'))->user()->name}}</span>, {{Helper::greet()}}!</div>

        <div class="dropdown">
            <div  class="user col align-self-end">
                <img src="{{asset('placeholder/user.png')}}" id="userDropdown" alt="" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">

                <div class="dropdown-menu dropdown-menu-right" aria-labelledby="userDropdown">
                    <div class="dropdown-header">
                        <i class="i-Lock-User mr-1"></i> {{Auth::guard((session()->get('is_admin','no') == "yes" ?'admin' : 'partner'))->user()->name}}
                    </div>
                    <a class="dropdown-item" href="{{route('portal.profile.edit_password')}}">Update Password</a>
                    <a class="dropdown-item" href="{{route('portal.logout')}}">Sign out</a>
                </div>
            </div>
        </div>
    </div>
</div>

resources/views/portal/components/nav.blade.php
<div class="side-content-wrap">
  <div class="sidebar-left open rtl-ps-none" data-perfect-scrollbar data-suppress-scroll-x="true">
  <ul class="navigation-left">
      <li class="nav-item">
          <a class="nav-item-hold" href="{{route('portal.index')}}">
              <i class="nav-icon i-Bar-Chart"></i>
              <span class="nav-text">Dashboard</span>
          </a>
          <div class="triangle"></div>
      </li>
      @if(session()->get('is_admin','no') == "yes")
      <li class="nav-item ">
          <a class="nav-item-hold" href="{{route('portal.partner.index')}}">
              <i class="nav-icon i-Business-Mens"></i>
              <span class="nav-text">Partners</span>
          </a>
          <div class="triangle"></div>
      </li>
      @endif
      <li class="nav-item">
          <a class="nav-item-hold" href="{{route('portal.reporting.index')}}">
              <i class="nav-icon i-Line-Chart"></i>
              <span class="nav-text">Reporting</span>
          </a>
          <div class="triangle"></div>
      </li>
      @if(session()->get('is_admin','no') == "yes")
      <li class="nav-item">
          <a class="nav-item-hold" href="{{route('portal.reporting.import')}}">
              <i class="nav-icon i-Data-Upload"></i>
              <span class="nav-text">Upload Sales</span>
          </a>
          <div class="triangle"></div>
      </li>
      @endif
      
      <li class="nav-item ">
          <a class="nav-item-hold" href="{{route('portal.barcode.index')}}">
              <i class="nav-icon i-Billing"></i>
              <span class="nav-text">Barcodes</span>
          </a>
          <div class="triangle"></div>
      </li>
      @if(session()->get('is_admin','no') == "yes")
      <li class="nav-item " >
          <a class="nav-item-hold" href="{{route('portal.administrator.index')}}">
              <i class="nav-icon i-Administrator"></i>
              <span class="nav-text">Administrators</span>
          </a>
          <div class="triangle"></div>
      </li>
      @endif

  </ul>
</div>
<div class="sidebar-overlay"></div>

resources/views/portal/components/notifications.blade.php
@if(session()->has('notification-status'))
  @if(session()->get('notification-status') == "success")
  <div role="alert" class="alert alert-success alert-dismissible">
    <div class="icon"><span class="mdi mdi-check"></span></div>
    <div class="message">
      <button type="button" data-dismiss="alert" aria-label="Close" class="close"><span aria-hidden="true" class="mdi mdi-close"></span></button>{{session()->get('notification-msg')}}
    </div>
  </div>
  @endif

  @if(session()->get('notification-status') == "info")
  <div role="alert" class="alert alert-info alert-dismissible">
    <div class="icon"><span class="mdi mdi-info-outline"></span></div>
    <div class="message">
      <button type="button" data-dismiss="alert" aria-label="Close" class="close"><span aria-hidden="true" class="mdi mdi-close"></span></button>{{session()->get('notification-msg')}}
    </div>
  </div>
  @endif

  @if(session()->get('notification-status') == "warning")
  <div role="alert" class="alert alert-warning alert-dismissible">
    <div class="icon"><span class="mdi mdi-alert-triangle"></span></div>
    <div class="message">
      <button type="button" data-dismiss="alert" aria-label="Close" class="close"><span aria-hidden="true" class="mdi mdi-close"></span></button>{{session()->get('notification-msg')}}
    </div>
  </div>
  @endif

  @if(session()->get('notification-status') == "failed" OR session()->get('notification-status') == "error")
  <div role="alert" class="alert alert-danger alert-dismissible">
    <div class="icon"><span class="mdi mdi-close-circle-o"></span></div>
    <div class="message">
      <button type="button" data-dismiss="alert" aria-label="Close" class="close"><span aria-hidden="true" class="mdi mdi-close"></span></button>{{session()->get('notification-msg')}}
    </div>
  </div>
  @endif
@endif