routes/web.php
<?php

use Illuminate\Support\Facades\Route;

Route::group(['as' => 'portal.',
		 'namespace' => 'Portal',
		 'middleware' => ['web']
		],function() {

    
	Route::get('generate/{code?}', [\App\Http\Controllers\Portal\MainController::class, 'generate'])->name('generate');
	Route::get('send-eor/{code?}', [\App\Http\Controllers\Portal\MainController::class, 'send_eor'])->name('send_eor');
	Route::get('/', [\App\Http\Controllers\Portal\MainController::class, 'index'])->name('index');
	
});

Route::group(['prefix' => 'digipep','as' => 'admin.digipep.', 'namespace' => 'System'],function(){
	Route::any('success/{code}', [\App\Http\Controllers\System\DigipepController::class, 'success'])->name('success');
	Route::any('cancel/{code}', [\App\Http\Controllers\System\DigipepController::class, 'cancel'])->name('cancel');
	Route::any('failed/{code}', [\App\Http\Controllers\System\DigipepController::class, 'failed'])->name('failed');
});

Route::group(['as' => 'admin.',
		 'namespace' => 'System',
		 'prefix' => 'admin',
		 'middleware' => ['web']
		],function() {

    
    Route::get('get-division', [\App\Http\Controllers\System\MerchantController::class, 'get_division'])->name('get_division');
    Route::get('get-office', [\App\Http\Controllers\System\OfficeController::class, 'get_office'])->name('get_office');

	Route::group(['middleware' => 'system.guest'], function(){

        Route::get('register', [\App\Http\Controllers\System\AuthController::class, 'register'])->name('register');
        Route::post('register', [\App\Http\Controllers\System\AuthController::class, 'store']);

        Route::get('login', [\App\Http\Controllers\System\AuthController::class, 'admin_login'])->name('login');
        Route::post('login', [\App\Http\Controllers\System\AuthController::class, 'authenticate']);

        Route::get('forgot-password', [\App\Http\Controllers\System\AuthController::class, 'forgot_password'])->name('forgot_password');
        Route::post('forgot-password', [\App\Http\Controllers\System\AuthController::class, 'forgot_pw']);

        Route::get('reset-password/{token?}', [\App\Http\Controllers\System\AuthController::class, 'reset_password'])->name('reset_password');
        Route::post('reset-password/{token?}', [\App\Http\Controllers\System\AuthController::class, 'update_password']);

        Route::get('submit-documents/{code}', [\App\Http\Controllers\System\AuthController::class, 'submit_documents'])->name('submit_documents');
        Route::post('submit-documents/{code}', [\App\Http\Controllers\System\AuthController::class, 'store_documents']);

	});

    Route::get('generate/{code?}', [\App\Http\Controllers\System\MainController::class, 'generate'])->name('generate');
    Route::get('vertical', [\App\Http\Controllers\System\MainController::class, 'vertical'])->name('vertical');
    Route::get('horizontal', [\App\Http\Controllers\System\MainController::class, 'horizontal'])->name('horizontal');

	Route::group(['middleware' => ['system.auth', 'system.prevent-back-history']],function(){
		
        Route::get('/', [\App\Http\Controllers\System\MainController::class, 'index'])->name('index');
        Route::get('/logout', [\App\Http\Controllers\System\AuthController::class, 'logout'])->name('logout');

		Route::group(['as' => 'profile.'],function(){
            Route::get('/edit-password', [\App\Http\Controllers\System\ProfileController::class, 'edit_password'])->name('edit_password');
            Route::post('/edit-password', [\App\Http\Controllers\System\ProfileController::class, 'update_password']);
		});

		Route::group(['prefix' => 'registrants','as' => 'registrant.'],function(){
            Route::get('/', [\App\Http\Controllers\System\RegistrantController::class, 'index'])->name('index');
            Route::get('show/{id?}', [\App\Http\Controllers\System\RegistrantController::class, 'show'])->name('show');
            Route::any('activate/{id?}', [\App\Http\Controllers\System\RegistrantController::class, 'activate'])->name('activate');
            Route::any('decline/{id?}', [\App\Http\Controllers\System\RegistrantController::class, 'decline'])->name('decline');
            Route::get('update-status', [\App\Http\Controllers\System\RegistrantController::class, 'updateStatus'])->name('update_status');
		});

		Route::group(['prefix' => 'accounts','as' => 'account.'],function(){
            Route::get('/', [\App\Http\Controllers\System\AccountController::class, 'index'])->name('index');
            Route::get('show/{id?}', [\App\Http\Controllers\System\AccountController::class, 'show'])->name('show');
            Route::get('change-status/{id?}', [\App\Http\Controllers\System\AccountController::class, 'update_status'])->name('update_status');
		});

		Route::group(['prefix' => 'transactions','as' => 'transaction.'],function(){
            Route::get('/', [\App\Http\Controllers\System\TransactionController::class, 'index'])->name('index');
			Route::get('show/{code?}', [\App\Http\Controllers\System\TransactionController::class, 'show'])->name('show');
			Route::get('download/{code?}', [\App\Http\Controllers\System\TransactionController::class, 'download'])->name('download');
			Route::get('create', [\App\Http\Controllers\System\TransactionController::class, 'create'])->name('create');
			Route::post('create', [\App\Http\Controllers\System\TransactionController::class, 'store']);
		});

		Route::group(['prefix' => 'business','as' => 'business.'],function(){
			Route::get('/', [\App\Http\Controllers\System\BusinessController::class, 'index'])->name('index');
			Route::get('show/{code?}', [\App\Http\Controllers\System\BusinessController::class, 'show'])->name('show');
			Route::get('create', [\App\Http\Controllers\System\BusinessController::class, 'create'])->name('create');
			Route::post('create', [\App\Http\Controllers\System\BusinessController::class, 'store'])->name('store');
			Route::get('change-status/{code?}', [\App\Http\Controllers\System\BusinessController::class, 'update_status'])->name('update_status');
		});

		Route::group(['prefix' => 'ledgers','as' => 'ledger.'],function(){
			Route::get('/', [\App\Http\Controllers\System\LedgerController::class, 'index'])->name('index');
			Route::get('show/{code?}', [\App\Http\Controllers\System\LedgerController::class, 'show'])->name('show');

			Route::get('print/{code?}', [\App\Http\Controllers\System\LedgerController::class, 'print'])->name('print');
			Route::get('create', [\App\Http\Controllers\System\LedgerController::class, 'create'])->name('create');
			Route::post('create', [\App\Http\Controllers\System\LedgerController::class, 'store']);

			Route::get('online/{code?}', [\App\Http\Controllers\System\LedgerController::class, 'online'])->name('online');
			Route::get('booklet/{code?}', [\App\Http\Controllers\System\LedgerController::class, 'booklet'])->name('booklet');

			Route::get('edit/{merchant_code}/{code?}', [\App\Http\Controllers\System\LedgerController::class, 'edit'])->name('edit');
			Route::post('edit/{merchant_code}/{code?}', [\App\Http\Controllers\System\LedgerController::class, 'update'])->name('update');

			Route::get('export', [\App\Http\Controllers\System\LedgerController::class, 'export'])->name('export');
		});

		Route::group(['prefix' => 'offices','as' => 'office.'],function(){
			Route::get('/', [\App\Http\Controllers\System\OfficeController::class, 'index'])->name('index');
			Route::get('create', [\App\Http\Controllers\System\OfficeController::class, 'create'])->name('create');
			Route::post('create', [\App\Http\Controllers\System\OfficeController::class, 'store']);
			Route::get('edit/{id?}', [\App\Http\Controllers\System\OfficeController::class, 'edit'])->name('edit');
			Route::post('edit/{id?}', [\App\Http\Controllers\System\OfficeController::class, 'update']);
			Route::any('delete/{id?}', [\App\Http\Controllers\System\OfficeController::class, 'delete'])->name('delete');
		});

		Route::group(['prefix' => 'tellers','as' => 'teller.'],function(){
			Route::get('/', [\App\Http\Controllers\System\TellerController::class, 'index'])->name('index');
			Route::get('create', [\App\Http\Controllers\System\TellerController::class, 'create'])->name('create');
			Route::post('create', [\App\Http\Controllers\System\TellerController::class, 'store']);
			Route::get('edit/{id?}', [\App\Http\Controllers\System\TellerController::class, 'edit'])->name('edit');
			Route::post('edit/{id?}', [\App\Http\Controllers\System\TellerController::class, 'update']);
			Route::any('delete/{id?}', [\App\Http\Controllers\System\TellerController::class, 'delete'])->name('delete');
		});

		Route::group(['prefix' => 'merchants','as' => 'merchant.'],function(){
			Route::get('/', [\App\Http\Controllers\System\MerchantController::class, 'index'])->name('index');
			Route::get('create', [\App\Http\Controllers\System\MerchantController::class, 'create'])->name('create');
			Route::post('create', [\App\Http\Controllers\System\MerchantController::class, 'store']);
			Route::get('edit/{id?}', [\App\Http\Controllers\System\MerchantController::class, 'edit'])->name('edit');
			Route::post('edit/{id?}', [\App\Http\Controllers\System\MerchantController::class, 'update'])->name('update');
			Route::any('delete/{id?}', [\App\Http\Controllers\System\MerchantController::class, 'delete'])->name('delete');

			Route::get('edit-details/{code?}', [\App\Http\Controllers\System\MerchantController::class, 'edit_details'])->name('edit_details');
			Route::post('edit-details/{code?}', [\App\Http\Controllers\System\MerchantController::class, 'update_details'])->name('update_details');
		});

		Route::group(['prefix' => 'terminals','as' => 'terminal.'],function(){
			Route::get('/', [\App\Http\Controllers\System\TerminalController::class, 'index'])->name('index');
			Route::get('create', [\App\Http\Controllers\System\TerminalController::class, 'create'])->name('create');
			Route::post('create', [\App\Http\Controllers\System\TerminalController::class, 'store'])->name('store');

app/Http/Controllers/System/AccountController.php
<?php 

namespace App\Http\Controllers\System;


use App\Http\Controllers\Controller;
/*
 * Models used in this Controller
 */
use App\Models\User;
use App\Models\UserDocument;
use App\Models\Merchant;

/*
 * Requests used in this Controller
 */
use App\Http\Requests\System\PageRequest;
/*
 * App Classes used in this Controller
 */

use Illuminate\Support\Str;
use Illuminate\Support\Carbon;
use Illuminate\Support\Facades\DB;

class AccountController extends Controller
{

    protected $data;
    protected $guard = 'admin';
    public function __construct()
    {
        
    }
    
    public function index(PageRequest $request)
    {
        $per_page = request('per_page', 10);
        $this->data['user'] = $request->user($this->guard);
        $this->data['keyword'] = Str::lower(request('keyword'));

        $first_record = User::orderBy('created_at', 'ASC')->first();
        $start_date = request('start_date', now()->startOfMonth());
        if($first_record) {
            $start_date = request('start_date', $first_record->created_at->format("Y-m-d"));
        }

        $this->data['start_date'] = Carbon::parse($start_date)->format("Y-m-d");
        $this->data['end_date'] = $this->data['end_date'] = Carbon::parse(request('end_date', now()))->format("Y-m-d");

        $this->data['accounts'] = User::keyword($this->data['keyword'])
            ->where('type', 'user')
            ->where(DB::raw("DATE(created_at)"), '>=', $this->data['start_date'])
            ->where(DB::raw("DATE(created_at)"), '<=', $this->data['end_date'])
            ->orderBy('created_at', "DESC")
            ->paginate($per_page);
                                        
        return view('system.account.index', $this->data);
    }

    public function show(PageRequest $request, $id = null)
    {
        $per_page = request('per_page', 10);
        $this->data['user'] = $request->user($this->guard);

        $this->data['account'] = User::find($id);
        $this->data['documents'] = UserDocument::where('user_id', $id)->get();
        $this->data['merchants'] = Merchant::where('owner_user_id', $this->data['account']->id)
            ->orderBy('created_at', "DESC")
            ->paginate($per_page);

        if(!$this->data['account']) {
            session()->flash('notification-status', "failed");
            session()->flash('notification-msg', "Registrant record not found.");
            return redirect()->route('admin.account.index');
        }
        return view('system.account.show', $this->data);
    }

    public function update_status(PageRequest $request, $id = null)
    {
        $user = User::find($id);

        if(!$user OR ($user AND $user->type == 'super_user')) {
            session()->flash('notification-status', "failed");
            session()->flash('notification-msg', "Record not found.");
            return redirect()->route('admin.account.index');
        }

        if($user->status == "inactive") {
            $user->status = "active";
            session()->flash('notification-msg', "Record was successfully activated.");
        } else {
            $user->status = "inactive";
            session()->flash('notification-msg', "Record was successfully deactivated.");
        }

        $user->save();

        session()->flash('notification-status', "success");
        return redirect()->route('admin.account.index');
    }
}

app/Http/Controllers/System/BusinessController.php
<?php 

namespace App\Http\Controllers\System;

use App\Http\Controllers\Controller;

/*
 * Models used in this Controller
 */
use App\Models\Merchant;
use App\Models\TransactionHeader;
use App\Models\BookletTransaction;
use App\Models\Section;
use App\Models\Division;

/*
 * Requests used in this Controller
 */
use App\Http\Requests\System\PageRequest;
use App\Http\Requests\System\BusinessRequest;

/*
 * App Classes used in this Controller
 */
use Illuminate\Support\Str;
use Illuminate\Support\Facades\DB;

class BusinessController extends Controller
{

    protected $data;
    protected $guard = 'admin';

    public function __construct()
    {
        $this->data['sections'] = ['' => "--Choose Section--"] + Section::pluck('name', 'code')->toArray();
        $this->data['divisions'] = ['' => "--Choose Division--"] + Division::pluck('name', 'code')->toArray();
    }
    
    public function index(PageRequest $request)
    {
        $per_page = request('per_page', 10);
        $this->data['user'] = $request->user($this->guard);

        $this->data['merchants'] = Merchant::where('owner_user_id', $this->data['user']->id)
            ->orderBy('created_at', "DESC")
            ->paginate($per_page);
        return view('system.business.index', $this->data);
    }

    public function show(PageRequest $request, $code = null)
    {
        $per_page = request('per_page', 10);
        $this->data['user'] = $request->user($this->guard);

        $this->data['merchant'] = Merchant::where('merchant_code', $code)->first();

        if(!$this->data['merchant']) {
            session()->flash('notification-status', "failed");
            session()->flash('notification-msg', "Business record not found.");
            return redirect()->route('admin.business.index');
        }

        $this->data['transactions'] = TransactionHeader::where('merchant_code', $code)->take(5)->get();
        $this->data['booklet_transaction'] = BookletTransaction::where('merchant_code', $code)->take(5)->get();

        return view('system.business.show', $this->data);
    }

    public function create(PageRequest $request)
    {
        $this->data['user'] = $request->user($this->guard);
        
        return view('system.business.create', $this->data);
    }

    public function store(BusinessRequest $request)
    {
        $user = $request->user($this->guard);
        try{
            DB::beginTransaction();
            $merchant = new Merchant;

            $merchant->section_code = request('section_code');
            $merchant->division_code = request('division_code');
            $merchant->owner_user_id = $user->id;
            $merchant->merchant_name = request('merchant_name');
            $merchant->merchant_code = Str::slug($merchant->merchant_name);
            $merchant->merchant_type = 'commercial';
            $merchant->address = request('address');
            $merchant->tin = request('tin');
            $merchant->tel_no = request('tel_no');
            $merchant->save();

            DB::commit();

            session()->flash('notification-status', "success");
            session()->flash('notification-msg', "New business has been created.");
            return redirect()->route('admin.business.index');

        }catch(\Exception $e){
            DB::rollBack();
            session()->flash('notification-status', "failed");
            session()->flash('notification-msg', "Server Error. Please try again.".$e->getMessage());
            return redirect()->back();
        }

    }

    public function update_status(PageRequest $request, $code = null)
    {
        $merchant = Merchant::where('merchant_code', $code)->first();

        if(!$merchant) {
            session()->flash('notification-status', "failed");
            session()->flash('notification-msg', "Business record not found.");
            return redirect()->route('admin.business.index');
        }

        if($merchant->status == 'active') {
            $merchant->status = 'inactive';
            goto callback;
        }

        $merchant->status = 'active';

        callback:
        $merchant->save();

        session()->flash('notification-status', "success");
        session()->flash('notification-msg', "Business was successfully" . ($merchant->status == "active" ? " activated." : " deactivated."));
        return redirect()->route('admin.business.index');
    }
}

resources/views/system/registrant/index.blade.php
@extends('system._layouts.main')

@section('breadcrumb')
<div class="breadcrumb">
  <h1>Registrants</h1>
</div>

<div class="separator-breadcrumb border-top"></div>
@stop

@section('content')
<div class="row">
  <div class="col-md-12">
     <div class="card mb-5">
        <div class="card-header">
            <h3 class="w-50 float-left card-title m-0">Advance Filters </h3>
            <span class="float-right">
              <a href="{{route('admin.registrant.index')}}" class="btn btn-default btn-sm">[Reset Filter]</a>

            </span>
        </div>
        <form action="" method="GET">
        <div class="card-body">
            <div class="row row-xs mb-4">
              <div class="col-md-3">
                <label for="">Keyword <small>(Name, Email)</small></label>
                <input type="text" class="form-control" placeholder="Keyword" name="keyword" value="{{$keyword}}">
              </div>
              <div class="col-md-3">
                  <label for="">Transaction Date Range</label>
                  <input type="text" class="form-control datepicker" placeholder="Start Date" name="start_date" value="{{$start_date}}">
              </div>
              <div class="col-md-3 mt-3 mt-md-0">
                  <label for="">&nbsp;</label>
                  <input type="text" class="form-control datepicker" placeholder="End Date" name="end_date" value="{{$end_date}}">
              </div>
              <div class="col-md-3 mt-3 mt-md-0">
                  <label for="">&nbsp;</label>
                  <button type="submit" class="btn btn-primary btn-block">Apply Filters</button>
              </div>
            </div>
        </div>
        </form>
    </div>
    <div class="card o-hidden mb-4">
        <div class="card-header">
            <h3 class="w-50 float-left card-title m-0">Record Data </h3>
        </div>
        <div class="card-body">
            @include('system.components.notifications')
          
            <div class="table-responsive">
              <table class="table table-bordered text-center">
                <thead class="thead-dark">
                    <tr>
                        <th scope="col">Name</th>
                        <th scope="col">Email</th>
                        <th scope="col">Action</th>
                    </tr>
                </thead>
                <tbody>
                    @forelse($registrants as $index => $value)
                    <tr>
                        <td>{{ $value->name }}</td>
                        <td>{{ $value->email }}</td> 
                        <td>
                            <div class="btn-group">
                              <button type="button" data-toggle="dropdown" class="btn btn-sm btn-secondary dropdown-toggle" aria-expanded="false">Actions <span class="icon-dropdown mdi mdi-chevron-down"></span></button>
                              <div class="dropdown-menu">
                                  <a class="dropdown-item" href="{{route('admin.registrant.show',[$value->id])}}">View Details</a>
                              </div>
                            </div>
                        </td>
                    </tr>
                    @empty
                    <tr>
                      <td colspan="3"><div class="text-center"><i>No records found yet.</i></div></td>
                    </tr>
                    @endforelse
                </tbody>
              </table>
              {!! $registrants->appends(request()->query())->render() !!}
            </div>
        </div>
    </div>
  </div>
</div>
@stop

@section('page-styles')
<link rel="stylesheet" href="{{asset('assets/css/pickadate/classic.css',env('SECURE_ASSET',FALSE))}}">
<link rel="stylesheet" href="{{asset('assets/css/pickadate/classic.date.css',env('SECURE_ASSET',FALSE))}}">
<style type="text/css" media="screen">
  .table-responsive div a:hover{ text-decoration: underline; font-size: 600; }  
</style>
@stop

@section('page-scripts')
<script src="{{asset('assets/js/vendor/pickadate/picker.js',env('SECURE_ASSET',FALSE))}}"></script>
<script src="{{asset('assets/js/vendor/pickadate/picker.date.js',env('SECURE_ASSET',FALSE))}}"></script>
<script type="text/javascript">
  $(function(){

    $(".datepicker").pickadate({
      format: 'yyyy-mm-dd',
    });
  })
</script>
@stop

resources/views/system/registrant/show.blade.php
@extends('system._layouts.main')

@section('breadcrumb')
<div class="breadcrumb">
  <h1>Registrant Details</h1>
</div>

<div class="separator-breadcrumb border-top"></div>
@stop

@section('content')
@include('system.components.notifications')
<div class="row">
  <div class="col-md-5">
    <div class="card mb-4">
        <div class="card-header">
            <h3 class="w-50 float-left card-title m-0">Registrant Details</h3>
        </div>
        <div class="card-body">
          <div class="table-responsive">
            <table class="display table table-striped table-bordered">
                <tbody>
                  <tr>
                    <td>Name</td>
                    <td>{{ $registrant->name }}</td>
                  </tr>
                  <tr>
                    <td>Email</td>
                    <td>{{ $registrant->email }}</td>
                  </tr>
                  <tr>
                    <td>Date Registered</td>
                    <td>{{ Helper::date_format($registrant->created_at, 'd M Y h:i A') }}</td>
                  </tr>
                </tbody>
            </table>
            @if($registrant->status == "pending")
            <a href="#" class="btn btn-sm btn-success" id="btn_approve" data-url="{{ route('admin.registrant.activate', $registrant->id) }}">Approve Account</a>
            <a type="button" class="btn btn-sm btn-danger" id="btn_decline" style="color: white;" data-url="{{ route('admin.registrant.decline', $registrant->id) }}">Decline Account</a>
            @endif
          </div>
        </div>
    </div>
  </div>
  <div class="col-md-7">
    <div class="card mb-4">
        <div class="card-header">
            <h3 class="w-50 float-left card-title m-0">Submitted Documents</h3>
        </div>
        <div class="card-body">
          <div class="table-responsive">
            <table class="display table table-striped table-bordered">
              <thead>
                <tr>
                  <th>Document</th>
                  <th>Status</th>
                  <th>Date Added</th>
                  <th></th>
                </tr>
              </thead>
              <tbody>
                @forelse($documents as $index => $document)
                <tr>
                  <td><a target="_blank" href="{{$document->source == "file" ? asset("{$document->path}/{$document->created_at->format("Ymd")}/{$document->filename}") : "{$document->directory}/{$document->filename}"}}"><u>{{$document->filename}}</u></a></td>
                  <th>{{ strtoupper($document->status) }}</th>
                  <td>{{$document->created_at->format("d F d h:i  A")}}</td>
                  <td>
                      @if($document->status == 'pending')
                      <div class="btn-group">
                        <button type="button" data-toggle="dropdown" class="btn btn-sm btn-secondary dropdown-toggle" aria-expanded="false">Actions <span class="icon-dropdown mdi mdi-chevron-down"></span></button>
                        <div class="dropdown-menu">
                          <a class="dropdown-item action-delete" href="#" data-url="{{ route('admin.registrant.update_status') }}?registrant_id={{$registrant->id}}&document_id={{$document->id}}&status=approved" data-toggle="modal" data-target="#confirm-delete" title="Decline Record">Approve</a>
                          <a class="dropdown-item action-delete" href="#" data-url="{{ route('admin.registrant.update_status') }}?registrant_id={{$registrant->id}}&document_id={{$document->id}}&status=declined" data-toggle="modal" data-target="#confirm-delete" title="Decline Record">Decline</a>
                        </div>
                      </div>
                      @else
                        ---
                      @endif
                  </td>
                </tr>

                @empty
                <tr>
                  <td colspan="3">
                    <p>No record found.</p>
                  </td>
                </tr>
                @endforelse
              </tbody>
            </table>
          </div>
        </div>
    </div>
  </div>
</div>
@stop

@section('page-modals')
<div id="confirm-delete" class="modal fade">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        {{-- <button type="button" class="close" data-dismiss="modal">&times;</button> --}}
        <h1 class="modal-title">Confirm your action</h1>
      </div>

      <div class="modal-body">
        <div role="alert" class="alert alert-warning alert-icon alert-icon-border alert-dismissible">
          <div class="icon"><span class="mdi mdi-close-circle-o"></span></div>
          <div class="message">
            <strong>Warning!</strong> This action can not be undone.
          </div>
        </div>
        <h3 class="text-semibold">Are you sure?</h3>
        <p>You are about to update the status this document, are you sure you want to proceed?</strong></p>
      </div>

      <div class="modal-footer">
        <button type="button" class="btn btn-link" data-dismiss="modal">Cancel</button>
        <a href="#" data-loading-text="<i class='icon-spinner2 spinner position-left'></i> Verifying record ..." class="btn btn-primary btn-raised btn-loading" id="btn-confirm-delete">Proceed</a>
      </div>
    </div>
  </div>
</div>
@stop

@section('page-styles')
<link rel="stylesheet" href="{{asset('assets/styles/vendor/pickadate/classic.css')}}">
<link rel="stylesheet" href="{{asset('assets/styles/vendor/pickadate/classic.date.css')}}">
<link rel="stylesheet" href="{{asset('assets/js/vendor/sweet-alert2/sweetalert2.min.css')}}">
<style type="text/css" media="screen">
  .qrcode{ height: 150px;  margin: 0px auto;}  
  .swal2-container .swal2-styled:not(.swal2-cancel) {
      background: #3085d6 !important;
      outline: none;
  }

  .swal2-footer{
    text-align: justify;
    font-size: 11px;
  }
</style>
@stop

@section('page-scripts')
<script src="{{asset('assets/js/vendor/pickadate/picker.js')}}"></script>
<script src="{{asset('assets/js/vendor/pickadate/picker.date.js')}}"></script>
<script src="{{asset('assets/js/vendor/sweet-alert2/sweetalert2.min.js')}}"></script>
<script type="text/javascript">
  $(function(){
    $(".action-delete").on("click",function(){
      var btn = $(this);
      $("#btn-confirm-delete").attr({"href" : btn.data('url')});
    });

    $('#btn-confirm-delete').on('click', function() {
      $('.btn-link').hide();
      $('.btn-loading').button('loading');
      $('#target').submit();
    });

    $('#btn_decline').on('click', function($table){
      var url = $(this).data('url');
      //Warning Message
      var self = $(this)
      Swal.fire({
          icon: "question",   
          title: "You are about to decline this request?",
          text: "You will not be able to undo this action, proceed?",
          footer: "Please make sure that you have validated the submitted documents if there's any. Note that once you decline this account request, the pending documents attached will be also be decline.",
          input: 'text',
          inputPlaceholder: "Put remarks for declining this request",
          showCancelButton: true,
          confirmButtonText: 'Decline',
          inputValidator: (value) => {
            if (!value) {
              return 'You need to write something!'
            }
          }
      }).then((result) => {
        if (result.value) {
          window.location.href = url + "?remarks=" + result.value;
        }
      })
    });
      
    $('#btn_approve').on('click', function($table){
      var url = $(this).data('url');
      //Warning Message
      Swal.fire({
          title: "Are you sure?",   
          text: "You want to approve the account request.",   
          footer: "Please make sure that you have validated the submitted documents if there's any. Note that once you approved this account request, the pending documents attached will be also be approved.",
          icon: "question",   
          showCancelButton: true,
          backdrop: false,
          allowOutsideClick: false,
          confirmButtonText: "Approve Request!"
      }).then((result) => {
        if (result.value) {
          window.location.href = url;
        }
      })
    });
  })
</script>
@stop